// Generated by `rakupp --exe` — native transpilation of a Raku program.
#include "Interpreter.h"
#include "Value.h"
#include <vector>
#include <string>
#include <iostream>
using namespace rakupp;
static Interpreter RT;   // provides builtins, method dispatch, coercions

static Value u_fib(ValueList);

static Value u_fib(ValueList __a) {
    Value v_n = rtPos(__a, 0);
    return (RT.boolify(applyArith("<", v_n, Value::integer(2LL))) ? (v_n) : (applyArith("+", u_fib(ValueList{applyArith("-", v_n, Value::integer(1LL))}), u_fib(ValueList{applyArith("-", v_n, Value::integer(2LL))}))));
    return Value::any();
}

static void __rakupp_register() {
}

int main(int argc, char** argv) {
    { std::vector<std::string> a; for (int i = 1; i < argc; i++) a.push_back(argv[i]); RT.setArgs(a); }
    __rakupp_register();
    try {
        RT.callBuiltin("say", {u_fib(ValueList{Value::integer(10LL)})});
    } catch (const RakuError& e) { std::cerr << e.message << "\n"; return 1; }
    catch (const std::exception& e) { std::cerr << "Internal error: " << e.what() << "\n"; return 3; }
    return 0;
}
