#!/usr/bin/env raku
# Bake the JavaScript runtime (src/js-rt/*.js, concatenated in name order) into
# src/JsRuntimeSrc.cpp, so `rakupp --target=js` writes the exact runtime it was
# built with — the same scheme as tools/grammar/gen-shim-src.raku.
#
#   rakupp tools/js/gen-rt-src.raku            # rewrite src/JsRuntimeSrc.cpp
#   rakupp tools/js/gen-rt-src.raku --check    # exit 1 if it is stale
#   rakupp tools/js/gen-rt-src.raku --js FILE  # write the assembled runtime as JS
#
# The runtime goes into the binary as an ARRAY of raw-string chunks under 15 KB
# each: MSVC caps one literal at 16 KB, and a single 200 KB literal would not
# compile there. jsRuntimeSource() joins them once at run time.

my $ROOT = $*PROGRAM.parent.parent.parent;
my @parts = dir($ROOT.add('src/js-rt')).grep(*.extension eq 'js').sort(*.basename);
die "gen-rt-src: no fragments in src/js-rt/" unless @parts;
my $js = @parts.map({ "// ---- {.basename} ----\n" ~ .slurp }).join("\n");

if @*ARGS[0] eq '--js' {
    @*ARGS[1].IO.spurt($js);
    exit 0;
}

die "gen-rt-src: the runtime contains the raw-string delimiter" if $js.contains(')RKJS"');

my @chunks;
my $limit = 15000;
my $pos = 0;
while $pos < $js.chars {
    my $len = min($limit, $js.chars - $pos);
    # cut on a line boundary so a chunk never ends inside a `\` escape or a token
    my $piece = $js.substr($pos, $len);
    if $pos + $len < $js.chars {
        my $nl = $piece.rindex("\n");
        $piece = $piece.substr(0, $nl + 1) if $nl.defined && $nl > 0;
    }
    @chunks.push($piece);
    $pos += $piece.chars;
}

my $out = q:to/HEADER/;
// GENERATED by tools/js/gen-rt-src.raku from src/js-rt/*.js — DO NOT EDIT
// (t/js/run.raku fails when this file is stale). The JavaScript runtime a
// `--target=js` program calls into, baked into the binary so the emitted
// program always gets the runtime it was compiled against.
#include <string>
namespace rakupp {
static const char* const kJsRtParts[] = {
HEADER
for @chunks -> $c {
    $out ~= 'R"RKJS(' ~ $c ~ ')RKJS",' ~ "\n";
}
$out ~= q:to/FOOTER/;
};
std::string jsRuntimeSource() {
    std::string s;
    for (const char* p : kJsRtParts) s += p;
    return s;
}
} // namespace rakupp
FOOTER

my $target = $ROOT.add('src/JsRuntimeSrc.cpp');
if @*ARGS[0] eq '--check' {
    if !$target.e || $target.slurp ne $out {
        note "src/JsRuntimeSrc.cpp is stale — run: rakupp tools/js/gen-rt-src.raku";
        exit 1;
    }
    say "src/JsRuntimeSrc.cpp is current";
    exit 0;
}
$target.spurt($out);
say "wrote src/JsRuntimeSrc.cpp: {@parts.elems} fragments, {$js.chars} chars, {@chunks.elems} chunks";
