#!/usr/bin/env rakupp
# Build the interactive page from the same engine the terminal uses.
#
#   rakupp showcase/fourier/tools/build.raku
#
# Three steps:
#   1. bundle    lib/Fourier.rakumod + web/api.raku -> build/engine.raku
#                (`--target=js` takes one file, so `use` and `unit module` go)
#   2. transpile build/engine.raku -> web/engine.js   (rakupp --target=js)
#   3. inline    web/index.html + web/engine.js -> web/fourier.html, one file
#
# Step 2 is the whole point of the showcase: the astronomy is written once,
# in Raku, and the browser runs that same code.

my $here = $?FILE.IO.parent.parent;
my $rakupp = $*EXECUTABLE.Str;

# ---- 1. bundle ------------------------------------------------------------
my @out = '# Generated by tools/build.raku — do not edit.',
          '# Edit lib/Fourier.rakumod and web/api.raku instead.';
for $here.add('lib/Fourier.rakumod'), $here.add('web/api.raku') -> $src {
    @out.push: |$src.slurp.lines.grep({
        !/^ \s* 'unit' \s+ 'module' / && !/^ \s* 'use' \s+ 'Fourier'/
    }), '';
}
$here.add('build').mkdir;
my $bundle = $here.add('build/engine.raku');
$bundle.spurt: @out.join("\n");
say "bundle     build/engine.raku      {@out.elems} lines";

# ---- 2. transpile ---------------------------------------------------------
my $js = $here.add('web/engine.js');
my $p = run $rakupp, '--target=js', '--standalone', $bundle.Str, '-o', $js.Str, :out, :err;
unless $p.exitcode == 0 {
    note $p.err.slurp(:close);
    note "transpile failed";
    exit 1;
}
$p.out.slurp(:close);
say "transpile  web/engine.js          {$js.s} bytes";

# ---- 3. inline ------------------------------------------------------------
my $html = $here.add('web/index.html').slurp;
my $tag = '<script src="engine.js"></script>';
unless $html.contains($tag) {
    note "no <script src=\"engine.js\"> in web/index.html";
    exit 1;
}
my $code = $js.slurp.subst(/ \n '//# sourceMappingURL=' \N* /, '');
$html = $html.subst($tag, "<script>\n" ~ $code ~ "\n</script>");
$here.add('web/fourier.html').spurt: $html;
say "inline     web/fourier.html       {$html.chars} bytes — one self-contained page";
