# DATA-PLAN P2: the `csv` tag's engine primitives, `rakupp-from-csv` and
# `rakupp-to-csv`.
#
# CSV is the one family in the plan with no ecosystem reference behind it:
# Text::CSV is a different surface, so CSV::Native IS the reference, and the
# primitives here are a port of its src/csv.c rather than a reimplementation.
# That makes the conformance question sharper than P1's, not softer — there is
# no third party to arbitrate, so what pins the two together is that the
# distribution carries a PURE-RAKU implementation of the same surface, run
# against its own C on every case its suite has.
#
# So the expectations below are not hand-written. They were generated by asking
# CSV::Native::Core::parse-raku and ::write-raku — the module's Raku half, which
# is independent of both its C and this port — and baked in as literals, because
# the distribution is deliberately NOT installed (the plan's rule: a *::Native
# module is a fallback for other engines, never a build dependency here).
# tools/... has no part in this; the generator lives in the notes.
#
# Regenerate with the recipe in raku-modules/notes/Data-Native.md if the module
# moves; a divergence shows up here as a failed row, naming the input.

use Test;

my &pf = &::('rakupp-from-csv');
my &pt = &::('rakupp-to-csv');

# `Nil` as the expectation means "the module dies here, and so must we". What
# it dies WITH is pinned separately below; this half only pins WHETHER.
sub check-parse($doc, %opt, $want) {
    my $got = try pf($doc, |%opt);
    if $want === Nil {
        nok $got.defined, "from-csv refuses {$doc.raku} {%opt.raku}, as the module does";
    }
    else {
        is-deeply $got, $want, "from-csv matches the module: {$doc.raku} {%opt.raku}";
    }
}

sub check-write($rows, %opt, $want) {
    my $got = try pt($rows, |%opt);
    if $want === Nil {
        nok $got.defined, "to-csv refuses {$rows.raku} {%opt.raku}, as the module does";
    }
    else {
        is $got, $want, "to-csv matches the module, byte for byte: {$rows.raku} {%opt.raku}";
    }
}

# ---- 1. indistinguishable from the module --------------------------------
check-parse("a,b\n1,2\n", {}, [["a", "b"], ["1", "2"]]);
check-parse("a,b\n1,2\n", {:headers(Bool::True)}, [{:a("1"), :b("2")},]);
check-parse("a,b\n1,2\n", {:strict(Bool::True)}, [["a", "b"], ["1", "2"]]);
check-parse("a,b\r\n1,2\r\n", {}, [["a", "b"], ["1", "2"]]);
check-parse("a,b\r\n1,2\r\n", {:headers(Bool::True)}, [{:a("1"), :b("2")},]);
check-parse("a,b\r\n1,2\r\n", {:strict(Bool::True)}, [["a", "b"], ["1", "2"]]);
check-parse("a,b\r1,2\r", {}, [["a", "b"], ["1", "2"]]);
check-parse("a,b\r1,2\r", {:headers(Bool::True)}, [{:a("1"), :b("2")},]);
check-parse("a,b\r1,2\r", {:strict(Bool::True)}, [["a", "b"], ["1", "2"]]);
check-parse("one\n", {}, [["one"],]);
check-parse("one\n", {:headers(Bool::True)}, []);
check-parse("one\n", {:strict(Bool::True)}, [["one"],]);
check-parse("\n", {}, [[""],]);
check-parse("\n", {:headers(Bool::True)}, []);
check-parse("\n", {:strict(Bool::True)}, [[""],]);
check-parse("", {}, []);
check-parse("", {:headers(Bool::True)}, []);
check-parse("", {:strict(Bool::True)}, []);
check-parse("a,,c\n", {}, [["a", "", "c"],]);
check-parse("a,,c\n", {:headers(Bool::True)}, []);
check-parse("a,,c\n", {:strict(Bool::True)}, [["a", "", "c"],]);
check-parse(",\n", {}, [["", ""],]);
check-parse(",\n", {:headers(Bool::True)}, Nil);
check-parse(",\n", {:strict(Bool::True)}, [["", ""],]);
check-parse("a,b\n1,2", {}, [["a", "b"], ["1", "2"]]);
check-parse("a,b\n1,2", {:headers(Bool::True)}, [{:a("1"), :b("2")},]);
check-parse("a,b\n1,2", {:strict(Bool::True)}, [["a", "b"], ["1", "2"]]);
check-parse("\"q\",\"w\"\n", {}, [["q", "w"],]);
check-parse("\"q\",\"w\"\n", {:headers(Bool::True)}, []);
check-parse("\"q\",\"w\"\n", {:strict(Bool::True)}, [["q", "w"],]);
check-parse("\"has,comma\",x\n", {}, [["has,comma", "x"],]);
check-parse("\"has,comma\",x\n", {:headers(Bool::True)}, []);
check-parse("\"has,comma\",x\n", {:strict(Bool::True)}, [["has,comma", "x"],]);
check-parse("\"say \"\"hi\"\"\",x\n", {}, [["say \"hi\"", "x"],]);
check-parse("\"say \"\"hi\"\"\",x\n", {:headers(Bool::True)}, []);
check-parse("\"say \"\"hi\"\"\",x\n", {:strict(Bool::True)}, [["say \"hi\"", "x"],]);
check-parse("\"two\nlines\",x\n", {}, [["two\nlines", "x"],]);
check-parse("\"two\nlines\",x\n", {:headers(Bool::True)}, []);
check-parse("\"two\nlines\",x\n", {:strict(Bool::True)}, [["two\nlines", "x"],]);
check-parse("\"\",x\n", {}, [["", "x"],]);
check-parse("\"\",x\n", {:headers(Bool::True)}, []);
check-parse("\"\",x\n", {:strict(Bool::True)}, [["", "x"],]);
check-parse("a b,c\n", {}, [["a b", "c"],]);
check-parse("a b,c\n", {:headers(Bool::True)}, []);
check-parse("a b,c\n", {:strict(Bool::True)}, [["a b", "c"],]);
check-parse("\x[FEFF]a,b\n", {}, [["a", "b"],]);
check-parse("\x[FEFF]a,b\n", {:headers(Bool::True)}, []);
check-parse("\x[FEFF]a,b\n", {:strict(Bool::True)}, [["a", "b"],]);
check-parse("a,b\n1\n", {}, [["a", "b"], ["1"]]);
check-parse("a,b\n1\n", {:headers(Bool::True)}, [{:a("1")},]);
check-parse("a,b\n1\n", {:strict(Bool::True)}, Nil);
check-parse("a,b\n1,2,3\n", {}, [["a", "b"], ["1", "2", "3"]]);
check-parse("a,b\n1,2,3\n", {:headers(Bool::True)}, Nil);
check-parse("a,b\n1,2,3\n", {:strict(Bool::True)}, Nil);
check-write([["a", "b"], [IntStr.new(1, "1"), IntStr.new(2, "2")]], {}, "a,b\n1,2\n");
check-write([["a", "b"], [IntStr.new(1, "1"), IntStr.new(2, "2")]], {:always-quote(Bool::True)}, "\"a\",\"b\"\n\"1\",\"2\"\n");
check-write([["a", "b"], [IntStr.new(1, "1"), IntStr.new(2, "2")]], {:eol("\r\n")}, "a,b\r\n1,2\r\n");
check-write([["x,y", "p"], ["q", "r"]], {}, "\"x,y\",p\nq,r\n");
check-write([["x,y", "p"], ["q", "r"]], {:always-quote(Bool::True)}, "\"x,y\",\"p\"\n\"q\",\"r\"\n");
check-write([["x,y", "p"], ["q", "r"]], {:eol("\r\n")}, "\"x,y\",p\r\nq,r\r\n");
check-write([["q\"z", "a"], ["b", "c"]], {}, "\"q\"\"z\",a\nb,c\n");
check-write([["q\"z", "a"], ["b", "c"]], {:always-quote(Bool::True)}, "\"q\"\"z\",\"a\"\n\"b\",\"c\"\n");
check-write([["q\"z", "a"], ["b", "c"]], {:eol("\r\n")}, "\"q\"\"z\",a\r\nb,c\r\n");
check-write([["two\nlines", "x"], ["y", "z"]], {}, "\"two\nlines\",x\ny,z\n");
check-write([["two\nlines", "x"], ["y", "z"]], {:always-quote(Bool::True)}, "\"two\nlines\",\"x\"\n\"y\",\"z\"\n");
check-write([["two\nlines", "x"], ["y", "z"]], {:eol("\r\n")}, "\"two\nlines\",x\r\ny,z\r\n");
check-write([["only", "x"],], {}, "only,x\n");
check-write([["only", "x"],], {:always-quote(Bool::True)}, "\"only\",\"x\"\n");
check-write([["only", "x"],], {:eol("\r\n")}, "only,x\r\n");
check-write([{:a(1), :b(2)}, {:a(3), :b(4)}], {}, "a,b\n1,2\n3,4\n");
check-write([{:a(1), :b(2)}, {:a(3), :b(4)}], {:always-quote(Bool::True)}, "\"a\",\"b\"\n\"1\",\"2\"\n\"3\",\"4\"\n");
check-write([{:a(1), :b(2)}, {:a(3), :b(4)}], {:eol("\r\n")}, "a,b\r\n1,2\r\n3,4\r\n");

# The corpus above is the shape of well-formed CSV. These are the shapes that
# are NOT, and they are where two implementations of one format actually part
# company — a quote where a quote may not be, a space where nothing may be, a
# record that ends in the wrong place. Generated from the same oracle.

check-parse("a\"b,c\n", {}, Nil);
check-parse(" \"x\",y\n", {}, Nil);
check-parse("\"x\" ,y\n", {}, Nil);
check-parse("\"x\",\n", {}, [["x", ""],]);
check-parse("\"unterminated\n", {}, Nil);
check-parse("a,b\r\n\r\n1,2\r\n", {}, [["a", "b"], [""], ["1", "2"]]);
check-parse("a\n\n", {}, [["a"], [""]]);
check-parse("\"a\"\"\",b\n", {}, [["a\"", "b"],]);
check-parse("a,b\rc,d\n", {}, [["a", "b"], ["c", "d"]]);
check-parse("\"\r\n\",x\n", {}, [["\r\n", "x"],]);
check-parse("a,b,\n", {}, [["a", "b", ""],]);
check-parse(",a\n", {}, [["", "a"],]);

# ---- 2. the dialect adverbs ----------------------------------------------
#
# Not generated: these vary the dialect rather than the document, and the point
# of each is legible enough to state directly.

is-deeply pf("a;b\n1;2\n", :sep(';')), [["a","b"],["1","2"]], ':sep picks the separator';
is-deeply pf("a|b\n", :sep('|')), [["a","b"],], 'including one the regex engine would treat as special';
is-deeply pf("'q,x',b\n", :quote("'")), [["q,x","b"],], ':quote picks the quote character';
is-deeply pf("a,b\n1,2\n", :headers(<x y>)),
          [{ x => "a", y => "b" }, { x => "1", y => "2" }],
   'a list :headers names the columns and consumes no line';
is pt([["a","b"]], :sep(';')), "a;b\n", 'to-csv honours :sep';
is pt([["a,b"]], :sep(';')), "a,b\n", 'and quotes for the separator in force, not for a comma';
is pt([["a;b"]], :sep(';')), "\"a;b\"\n", '— which it does quote';
is pt([["a","b"]], :quote("'"), :always-quote), "'a','b'\n", 'and :quote';
is pt([["a"], ["b"]], :headers(<h>)), "h\na\nb\n", 'a list :headers writes a header line';
is pt([{ a => 1 }], :headers(<b a>)), "b,a\n,1\n", 'and orders and fills the hash rows by it';
is pt([{ a => 1, b => 2 }], :!headers), "1,2\n", 'an explicit :!headers suppresses the line';

# ---- 3. the IO surfaces --------------------------------------------------
#
# The primitive's surface is the MODULE's, not the C's: from-csv takes a Str, an
# IO::Path or an IO::Handle, because that is what a caller of
# `use Data::Native <csv>` writes.

my $tmp = $*TMPDIR.add("rakupp-csv-{$*PID}.csv");
$tmp.spurt("a,b\n1,2\n");
LEAVE { $tmp.unlink }
is-deeply pf($tmp), [["a","b"],["1","2"]], 'from-csv reads an IO::Path';
{
    my $fh = $tmp.open(:r);
    LEAVE $fh.close;
    is-deeply pf($fh), [["a","b"],["1","2"]], 'and an IO::Handle';
}

# ---- 4. what the primitives refuse ---------------------------------------

is-deeply pf(42), [["42"],],
   'a non-Str non-IO argument goes through .Str, which is the module\'s last arm';
throws-like { pf() }, X::AdHoc, message => /'expected something to read'/,
    'but there has to be an argument';
throws-like { pf("a\n", :sep('')) }, X::AdHoc, message => /'sep must not be empty'/,
    'an empty :sep is refused rather than looping';
throws-like { pf("a\n", :quote('xy')) }, X::AdHoc, message => /'exactly one character'/,
    'and a multi-character :quote — counted in CHARACTERS, so this is two';
is-deeply pf("\x[00AB]q,x\x[00AB],b\n", :quote("\x[00AB]")), [["q,x","b"],],
   'while a multi-BYTE quote is one character and legal';
throws-like { pf("a\n", :sep(',,'), :quote(',')) }, X::AdHoc,
    message => /'must not contain the quote'/,
    'a :sep containing the quote character cannot be tokenised, and says so';
throws-like { pf("a\n", :sep("\n")) }, X::AdHoc, message => /'line ending'/,
    'nor may a separator be a line ending';
throws-like { pf("a,b\n1,2\n", :headers(42)) }, X::AdHoc, message => /'Bool or a list'/,
    ':headers is a Bool or a list of names, and nothing else';
throws-like { pt(42) }, X::AdHoc, message => /'expected a list of rows'/,
    'to-csv wants a list of rows';
throws-like { pt([1]) }, X::AdHoc, message => /'not a list or a hash'/,
    'and each row a list or a hash — naming which row';
throws-like { pt([["a"], { b => 1 }]) }, X::AdHoc, message => /'no headers are known'/,
    'a hash row with no headers to project onto is refused rather than guessed';
throws-like { pt([["a"]], :eol('!')) }, X::AdHoc, message => /'eol must be'/,
    'and :eol is one of the three line endings';

# The parse errors name the line, which is the whole reason to raise rather
# than return a short row.
throws-like { pf("a,b\n1\n", :strict) }, X::AdHoc, message => /'line 2'/,
    ':strict reports the line the row count went wrong on';

# ---- 5. the backend name -------------------------------------------------

is &::('rakupp-csv-backend')(), 'core',
   "csv-backend says 'core' — the engine answered, no module did";

# ---- 6. the compiler answering a `use` must not pollute anything ----------
#
# Same shape as data-native-json.raku's section 5, and for the same reason: the
# primitives are registered as builtins, so a bare `from-csv` must stay
# undeclared until a `use` asks for it. Separate processes, because an
# undeclared routine is a COMPILE error and `try` cannot see one.

my $exe = $*EXECUTABLE.absolute;
sub compiles(Str $code) { run($exe, '-e', $code, :out, :err).exitcode == 0 }

nok compiles('from-csv("a,b")'), 'from-csv is undeclared without a `use`';
nok compiles('to-csv([["a"]])'), 'and to-csv';
nok compiles('csv-backend()'),   'and csv-backend';
nok compiles('say (&::("from-csv")).defined || die "visible"'),
    'and it is not reachable by runtime lookup either';
ok compiles('&::("rakupp-from-csv")("a,b")'),
   'the rakupp- primitive is reachable, which is the adoption mechanism';

ok compiles('{ use Data::Native <csv>; from-csv("a,b") }'),
   'a `use` inside a block works there';
nok compiles('{ use Data::Native <csv>; from-csv("a,b") }; from-csv("a,b")'),
    'and does not escape the block';
nok compiles('use Data::Native <csv>; to-json(1)'),
    'an unclaimed tag contributes no names';

# ---- 7. the claim registry, so CSV::Native stands aside -------------------

ok compiles('use Data::Native <csv>;
             die "not claimed" unless (PROCESS::<%DATA-NATIVE-CLAIMED> // {})<csv>;'),
   'the compiler writes the claim registry, as CSV::Native\'s EXPORT would';
ok compiles('use Data::Native <csv>;
             die "over-claimed" if (PROCESS::<%DATA-NATIVE-CLAIMED> // {})<json>;'),
   'and claims only the tags that were asked for';
ok compiles('use Data::Native <csv>; use Data::Native <json>;
             my %c = PROCESS::<%DATA-NATIVE-CLAIMED>;
             die "missing" unless %c<csv> && %c<json>;'),
   'two `use`s accumulate in the registry rather than replacing it';

done-testing;
