# Regenerates src/GrammarShim.cpp from the canonical shim source, so the
# grammar service's Raku half travels INSIDE librakupp (rk_grammar_shim) and
# no binding ever ships a sidecar copy that could skew against its engine.
#
#   rakupp tools/grammar/gen-shim-src.raku            # rewrite src/GrammarShim.cpp
#   rakupp tools/grammar/gen-shim-src.raku --check    # exit 1 if it is stale
#
# grammar-smoke runs the --check form: an edit to grammar_shim.raku without a
# regen fails the gate rather than shipping two versions of the truth.
# (The canonical source lives in the PYTHON package because pip needs its
# package data physically inside the package directory; every other binding
# reads the engine's baked copy.)

my $ROOT = $?FILE.IO.parent.parent.parent;
my $shim = $ROOT.add('bindings/python/rakulang/grammar_shim.raku');
my $out  = $ROOT.add('src/GrammarShim.cpp');

my $text = $shim.slurp;
die "gen-shim-src: the shim contains the raw-string delimiter" if $text.contains(')RKSHIM"');

my $src = q:to/HEADER/ ~ $text ~ q:to/FOOTER/;
// GENERATED by tools/grammar/gen-shim-src.raku from
// bindings/python/rakulang/grammar_shim.raku — DO NOT EDIT (grammar-smoke
// fails when this file is stale). The grammar service's Raku half, baked
// into librakupp so rk_grammar_shim() hands every host binding the exact
// shim its engine was built with.
namespace rakupp {
const char* grammarShimSource() {
    return R"RKSHIM(
HEADER
)RKSHIM";
}
} // namespace rakupp
FOOTER

if @*ARGS.grep('--check') {
    if !$out.e || $out.slurp ne $src {
        note "src/GrammarShim.cpp is STALE — run: rakupp tools/grammar/gen-shim-src.raku";
        exit 1;
    }
    say 'GrammarShim.cpp is current';
}
else {
    $out.spurt($src);
    say "wrote {$out} ({$src.chars} chars)";
}
