#!/usr/bin/env rakupp
# build.raku — assembles the Excel add-in and the Google Sheets script.
#
#   rakupp bindings/spreadsheets/build.raku --base=https://example.org/raku-excel/
#
# writes dist/excel (the files to serve, and the manifest that points at
# them) and dist/google-sheets (the files of an Apps Script project). Both
# carry the same engine, a Raku.js build (rakujs/playground by default).

use JSON::Fast;

my $HERE = $*PROGRAM.IO.absolute.IO.parent;
my $ROOT = $HERE.parent.parent;

sub MAIN(
    Str :$base   = 'https://localhost:3000/',   #= HTTPS address the Excel files will be served from, ending in /
    Str :$rakujs = ~$ROOT.add('rakujs/playground'),   #= directory holding rakujs.js and rakujs.wasm
    Str :$out    = ~$HERE.add('dist'),           #= where to write excel/ and google-sheets/
) {
    die "--base must end with a slash: $base\n" unless $base.ends-with('/');
    note "warning: Excel loads add-ins over HTTPS only; $base will not work there" unless $base.starts-with('https://');
    my $engine-js   = $rakujs.IO.add('rakujs.js');
    my $engine-wasm = $rakujs.IO.add('rakujs.wasm');
    die "no Raku.js build in $rakujs (run rakujs/build.sh)\n" unless $engine-js.e && $engine-wasm.e;

    my $version = repo-version();
    my $tag     = DateTime.now.posix.base(36).lc;
    my $core    = $HERE.add('core/rakusheet-core.js').slurp
                    .subst("'@RAKUSHEET_DRIVER@'", to-json($HERE.add('rakusheet.raku').slurp));
    die "core/rakusheet-core.js lost its @RAKUSHEET_DRIVER@ slot\n" if $core.contains('@RAKUSHEET_DRIVER@');

    build-excel($out.IO.add('excel'), :$base, :$version, :$tag, :$core, :$engine-js, :$engine-wasm);
    build-sheets($out.IO.add('google-sheets'), :$core, :$engine-js, :$engine-wasm);
}

# CMakeLists.txt's VERSION, as the four numbers an Office manifest wants.
sub repo-version(--> Str) {
    my $cmake = $ROOT.add('CMakeLists.txt').slurp;
    my $v = ($cmake ~~ / VERSION \s+ (\d+ '.' \d+ '.' \d+) /) ?? ~$0 !! '0.0.0';
    "$v.0"
}

sub fresh(IO::Path $dir) {
    if $dir.d {
        for $dir.dir -> $f { $f.d ?? fresh($f) !! $f.unlink }
    }
    $dir.mkdir;
    $dir
}

sub fill(Str $text, %slots --> Str) {
    my $t = $text;
    for %slots.kv -> $k, $v { $t = $t.subst('@' ~ $k ~ '@', $v, :g) }
    die 'an unfilled slot is left: @' ~ $0 ~ "@\n" if $t ~~ / '@' (<[A..Z_]>+) '@' /;
    $t
}

sub build-excel(IO::Path $dir, :$base, :$version, :$tag, :$core, :$engine-js, :$engine-wasm) {
    fresh($dir);
    my %slots = BASE => $base, VERSION => $version, TAG => $tag;
    for <manifest.xml functions.json functions.js taskpane.html taskpane.css taskpane.js rakusheet-worker.js> -> $f {
        $dir.add($f).spurt: fill($HERE.add("excel/$f").slurp, %slots);
    }
    $dir.add('rakusheet-core.js').spurt: $core;
    $dir.add('rakujs.js').spurt: $engine-js.slurp;
    $dir.add('rakujs.wasm').spurt: $engine-wasm.slurp(:bin);
    my $assets = $dir.add('assets');
    $assets.mkdir;
    for 16, 32, 64, 80, 128 -> $size {
        $assets.add("icon-$size.png").spurt: icon($size);
    }
    say "excel:         $dir  (manifest points at $base)";
}

sub build-sheets(IO::Path $dir, :$core, :$engine-js, :$engine-wasm) {
    fresh($dir);
    # gzip -n leaves the name and the time out, so that the same engine
    # always gives the same files.
    my $gz = run('gzip', '-9', '-n', '-c', ~$engine-wasm, :out, :bin).out.slurp(:close);
    my $b64 = base64($gz);
    my constant CHUNK = 1_000_000;   # characters per file, a multiple of 4
    my @parts = (0, CHUNK ...^ * >= $b64.chars).map({ $b64.substr($_, CHUNK) });

    $dir.add('appsscript.json').spurt: $HERE.add('google-sheets/appsscript.json').slurp;
    $dir.add('Raku.gs').spurt: $HERE.add('google-sheets/Raku.js').slurp;
    $dir.add('RakuLoader.gs').spurt: fill($HERE.add('google-sheets/RakuLoader.js').slurp, %(WASM_COUNT => @parts.elems));
    $dir.add('RakuCore.gs').spurt: $core;
    $dir.add('RakuEngine.gs').spurt: "// RakuEngine.gs — Raku.js, the Raku++ engine's JavaScript side. Generated by build.raku.\n" ~ $engine-js.slurp;
    for @parts.kv -> $i, $part {
        my $n = sprintf('%02d', $i + 1);
        $dir.add("RakuWasm$n.gs").spurt:
            "// RakuWasm$n.gs — part {$i + 1} of {+@parts} of the Raku engine, gzip and base64. Generated by build.raku.\n"
            ~ "var RAKUSHEET_WASM = typeof RAKUSHEET_WASM === 'undefined' ? [] : RAKUSHEET_WASM;\n"
            ~ "RAKUSHEET_WASM[$i] = \"$part\";\n";
    }
    say "google-sheets: $dir  ({+@parts} engine files, {($gz.elems / 1048576).fmt('%.1f')} MB compressed)";
}

sub base64(Blob $b --> Str) {
    my @a = |('A'..'Z'), |('a'..'z'), |('0'..'9'), '+', '/';
    my @quads;
    my $n = $b.elems;
    my $i = 0;
    while $i + 3 <= $n {
        my $v = $b[$i] +< 16 +| $b[$i + 1] +< 8 +| $b[$i + 2];
        @quads.push: @a[$v +> 18] ~ @a[($v +> 12) +& 63] ~ @a[($v +> 6) +& 63] ~ @a[$v +& 63];
        $i += 3;
    }
    if $n - $i == 1 {
        my $v = $b[$i] +< 16;
        @quads.push: @a[$v +> 18] ~ @a[($v +> 12) +& 63] ~ '==';
    }
    elsif $n - $i == 2 {
        my $v = $b[$i] +< 16 +| $b[$i + 1] +< 8;
        @quads.push: @a[$v +> 18] ~ @a[($v +> 12) +& 63] ~ @a[($v +> 6) +& 63] ~ '=';
    }
    @quads.join
}

# ---- the icon: a white R++ on an indigo rounded square, drawn here so that
# ---- the repository holds no binary files.

my constant BG = (0x43, 0x38, 0xCA);

sub in-square(Num $x, Num $y --> Bool) {
    my $r = 0.2e0;
    my $dx = max(abs($x - 0.5e0) - (0.5e0 - $r), 0e0);
    my $dy = max(abs($y - 0.5e0) - (0.5e0 - $r), 0e0);
    $dx * $dx + $dy * $dy <= $r * $r
}

# The R, drawn in a unit box and placed by in-glyph.
sub in-letter(Num $x, Num $y --> Bool) {
    return True if 0.28e0 <= $x <= 0.42e0 && 0.18e0 <= $y <= 0.82e0;                 # stem
    return True if 0.28e0 <= $x <= 0.50e0 && (0.18e0 <= $y <= 0.30e0 || 0.50e0 <= $y <= 0.62e0);   # bars
    if $x >= 0.50e0 {                                                                 # bowl
        my $d = sqrt(($x - 0.50e0) ** 2 + ($y - 0.40e0) ** 2);
        return True if 0.10e0 <= $d <= 0.22e0;
    }
    # the leg: within 0.065 of the segment (0.50, 0.56)–(0.74, 0.82)
    my ($ax, $ay, $bx, $by) = 0.50e0, 0.56e0, 0.74e0, 0.82e0;
    my $t = (($x - $ax) * ($bx - $ax) + ($y - $ay) * ($by - $ay)) / (($bx - $ax) ** 2 + ($by - $ay) ** 2);
    $t = min(max($t, 0e0), 1e0);
    my $d = sqrt(($x - $ax - $t * ($bx - $ax)) ** 2 + ($y - $ay - $t * ($by - $ay)) ** 2);
    $d <= 0.065e0 && $y <= 0.82e0
}

# The R, scaled to 0.70 and moved left, then two pluses on its middle line.
sub in-glyph(Num $x, Num $y --> Bool) {
    my $scale = 0.70e0;
    return True if in-letter(($x + 0.096e0) / $scale, ($y - 0.15e0) / $scale);
    in-plus($x, $y, 0.615e0) || in-plus($x, $y, 0.835e0)
}

sub in-plus(Num $x, Num $y, Num $cx --> Bool) {
    my ($arm, $half) = 0.095e0, 0.040e0;
    my ($dx, $dy) = abs($x - $cx), abs($y - 0.50e0);
    ($dx <= $arm && $dy <= $half) || ($dx <= $half && $dy <= $arm)
}

sub icon(Int $s --> Blob) {
    my $pixels = Buf.new;
    for ^$s -> $py {
        for ^$s -> $px {
            my ($back, $fore) = 0, 0;
            for ^4 -> $sy {
                for ^4 -> $sx {
                    my $x = ($px + ($sx + 0.5e0) / 4e0) / $s;
                    my $y = ($py + ($sy + 0.5e0) / 4e0) / $s;
                    next unless in-square($x, $y);
                    in-glyph($x, $y) ?? $fore++ !! $back++;
                }
            }
            my $covered = $back + $fore;
            if $covered == 0 { $pixels.append(0, 0, 0, 0); next }
            my $white = $fore / $covered;
            $pixels.append(|BG.map({ ($_ * (1 - $white) + 255 * $white).round }), ($covered / 16 * 255).round);
        }
    }
    png($s, $s, $pixels)
}

sub be32(Int $n --> Blob) { Blob.new(($n +> 24) +& 255, ($n +> 16) +& 255, ($n +> 8) +& 255, $n +& 255) }

sub crc32(Blob $b --> Int) {
    state @table = (^256).map: -> $n {
        my $c = $n;
        for ^8 { $c = $c +& 1 ?? 0xEDB88320 +^ ($c +> 1) !! $c +> 1 }
        $c
    };
    my $c = 0xFFFFFFFF;
    for $b.list -> $byte { $c = @table[($c +^ $byte) +& 255] +^ ($c +> 8) }
    $c +^ 0xFFFFFFFF
}

sub adler32(Blob $b --> Int) {
    my ($a, $s) = 1, 0;
    for $b.list -> $byte {
        $a = ($a + $byte) % 65521;
        $s = ($s + $a) % 65521;
    }
    $s +< 16 +| $a
}

sub png-chunk(Str $type, Blob $data --> Blob) {
    my $t = $type.encode('ascii');
    be32($data.elems) ~ $t ~ $data ~ be32(crc32($t ~ $data))
}

# RGBA, 8 bits a channel, no filtering, and DEFLATE's stored blocks: an icon
# is a few kilobytes either way.
sub png(Int $w, Int $h, Blob $rgba --> Blob) {
    my $raw = Buf.new;
    for ^$h -> $y {
        $raw.append(0);
        $raw.append($rgba.subbuf($y * $w * 4, $w * 4));
    }
    my $z = Buf.new(0x78, 0x01);
    my $pos = 0;
    while $pos < $raw.elems {
        my $len = min(65535, $raw.elems - $pos);
        my $final = $pos + $len >= $raw.elems ?? 1 !! 0;
        $z.append($final, $len +& 255, $len +> 8, +^$len +& 255, (+^$len +> 8) +& 255);
        $z.append($raw.subbuf($pos, $len));
        $pos += $len;
    }
    $z.append(be32(adler32($raw)));
    Blob.new(137, 80, 78, 71, 13, 10, 26, 10)
        ~ png-chunk('IHDR', be32($w) ~ be32($h) ~ Blob.new(8, 6, 0, 0, 0))
        ~ png-chunk('IDAT', $z)
        ~ png-chunk('IEND', Blob.new)
}
