#!/usr/bin/env raku
# Bake `rakupp doc` into the CLI: tools/doc.raku with docs/guide/REFERENCE.md
# and FEATURES.md spliced into its `%DOCS` declaration, written to
# src/DocToolSrc.cpp. That is why `rakupp doc trim` answers from an executable
# with nothing beside it.
#
#   rakupp tools/gen-doc-tool-src.raku          # rewrite src/DocToolSrc.cpp
#   rakupp tools/gen-doc-tool-src.raku --check  # exit 1 if it is stale
#
# The installer is NOT here. src/InstallerSrc.cpp is hand-maintained — it is the
# only copy of that program, with no .raku beside it. The doc tool cannot be:
# its blob contains the two guides, and those have their own source of truth in
# docs/guide/, so a hand-kept copy would drift the moment a guide is edited.
# Generating it means an edit to REFERENCE.md is either regenerated or caught
# by t/install/run.raku, never shipped stale.
#
# Same shape as tools/js/gen-rt-src.raku: an ARRAY of raw-string chunks under
# 15 KB each, because MSVC caps one string literal at 16 KB. The file is checked
# in rather than generated by CMake — generating it needs a working rakupp,
# which is the thing being built.

my $ROOT = $?FILE.IO.parent.parent;

# doc.raku declares `my %DOCS;` and reads it before it goes looking on disk;
# filling that declaration in is the whole of the embed.
constant DOC-END = 'RAKUPP-EMBED-END';

sub doc-source() {
    my $text = $ROOT.add('tools/doc.raku').slurp;
    my $marker = $text.lines.first(*.starts-with('my %DOCS;'));
    die "gen-doc-tool-src: tools/doc.raku no longer declares `my %DOCS;`" without $marker;

    my $fill = "my %DOCS;\n";
    for 'REFERENCE.md', 'FEATURES.md' -> $name {
        my $md = $ROOT.add("docs/guide/$name").slurp;
        $md ~= "\n" unless $md.ends-with("\n");
        die "gen-doc-tool-src: $name contains a line spelled {DOC-END}"
            if $md.lines.first(* eq DOC-END).defined;
        $fill ~= "%DOCS\{'$name'\} = Q:to/{DOC-END}/;\n" ~ $md ~ DOC-END ~ "\n";
    }
    $text.subst($marker, $fill.chomp)
}

# Cut on line boundaries so a chunk never ends inside a token; a raw string
# needs no escaping, but a delimiter collision would still end the literal.
sub chunks(Str $s) {
    die "gen-doc-tool-src: the doc tool contains the raw-string delimiter"
        if $s.contains(')RKDOC"');
    my @out;
    my $pos = 0;
    while $pos < $s.chars {
        my $piece = $s.substr($pos, min(15000, $s.chars - $pos));
        if $pos + $piece.chars < $s.chars {
            my $nl = $piece.rindex("\n");
            $piece = $piece.substr(0, $nl + 1) if $nl.defined && $nl > 0;
        }
        @out.push($piece);
        $pos += $piece.chars;
    }
    @out
}

my $doc = doc-source();

my $out = q:to/HEADER/;
// GENERATED by tools/gen-doc-tool-src.raku from tools/doc.raku and
// docs/guide/{REFERENCE,FEATURES}.md — DO NOT EDIT (t/install/run.raku fails
// when this file is stale). The `rakupp doc` program with both guides baked
// into it, so a lone binary can answer a lookup.
//
// The installer's copy is NOT generated: see src/InstallerSrc.cpp, which is
// that program's only copy. This one is, because the guides below are living
// documents with their own source in docs/guide/ — a hand-kept copy would
// drift the moment one is edited.
//
// CLI-ONLY (CMakeLists.txt): main.cpp is the sole caller, so no `--exe`
// binary and no embedder carries a byte of it.
#include "EmbeddedTools.h"
namespace rakupp {
static const char* const kDocParts[] = {
HEADER
$out ~= 'R"RKDOC(' ~ $_ ~ ')RKDOC",' ~ "\n" for chunks($doc);
$out ~= q:to/FOOTER/;
};
std::string docToolSource() {
    std::string s;
    for (const char* p : kDocParts) s += p;
    return s;
}
} // namespace rakupp
FOOTER

my $target = $ROOT.add('src/DocToolSrc.cpp');
if @*ARGS[0] eq '--check' {
    if !$target.e || $target.slurp ne $out {
        note "src/DocToolSrc.cpp is stale — run: rakupp tools/gen-doc-tool-src.raku";
        exit 1;
    }
    say "src/DocToolSrc.cpp is current";
    exit 0;
}
$target.spurt($out);
say "wrote src/DocToolSrc.cpp: {$doc.chars} chars";
