#!/usr/bin/env raku
# Generates src/exception_ancestry_gen.cpp — the X:: exception hierarchy.
#
#   raku tools/gen-exception-ancestry.raku > src/exception_ancestry_gen.cpp
#
# RUNS UNDER RAKUDO, not rakupp: the table IS Rakudo's own metamodel, read off a
# live `X::` package walk, and the point is to copy it rather than to re-derive
# it by hand. Rakudo is an oracle here, not a build dependency — the output is
# committed, and this file is re-run only when a Rakudo release moves the
# hierarchy underneath us.
#
# What the table holds is only what a name conforms to BEYOND itself: every
# X:: class is an Exception (and so an Any and a Mu) whether or not it is
# listed, so those three are implied and left out. Class ancestors come first,
# in MRO order, then the roles the class does — `.^mro` filters the roles back
# out by asking isExceptionRole, so their position among them does not matter.

my @names;
sub walk($pkg, $prefix) {
    for (try $pkg.WHO.keys) // () -> $k {
        my $full = $prefix ?? "$prefix\::$k" !! $k;
        @names.push: $full;
        walk($pkg.WHO{$k}, $full) if (try $pkg.WHO{$k}.WHO.keys.elems);
        CATCH { default {} }
    }
}
walk(X, 'X');

my %extras;     # class -> [names beyond itself/Exception/Any/Mu]
my %isrole;     # every X:: name that is a role, not a class
for @names.unique.sort -> $n {
    my $t   = ::($n);
    my $how = $t.HOW.^name;
    if $how.contains('Role') { %isrole{$n} = True; next }
    next unless $how.contains('ClassHOW');
    my @anc  = $t.^mro.map(*.^name).grep({ $_ ne $n && .starts-with('X::') });
    my @role = ((try $t.^roles(:transitive).map(*.^name)) // ()).grep(*.starts-with('X::'));
    my @extra = (|@anc, |@role).unique;
    %extras{$n} = @extra if @extra;
}

# A role reached only through another role (X::Syntax does no role, but the
# classes that do it also do X::Comp) still has to answer isExceptionRole, so
# take the role names from the extras as well as from the package walk.
%isrole{$_} = True for %extras.values.flat.grep({ (try ::($_).HOW.^name.contains('Role')) });

my $ver = $*RAKU.compiler.version;
say q:to/HEAD/.subst('%VER%', $ver);
// GENERATED by tools/gen-exception-ancestry.raku — do not edit.
// Source: Rakudo %VER%'s own `X::` metamodel.
//
// Raku's exception types are a hierarchy, and code reads it: `CATCH { when
// X::IO {…} }` wants every I/O failure, and Roast asserts on a supertype
// nearly as often as on a leaf (`throws-like …, X::Comp` 48 times, `X::TypeCheck`
// 66). rakupp used to answer every one of those False — its X:: names were
// bare type objects with no parents and no roles, so `X::TypeCheck::Binding::
// Parameter ~~ X::TypeCheck::Binding` was False and only an exact name matched.
//
// Each row lists what a name conforms to BEYOND itself, Exception, Any and Mu,
// which are implied for every X:: name — including one absent from the table,
// because a user's own `X::Mine` is an Exception too. Class ancestors come
// first in MRO order, then the roles; `.^mro` drops the roles by asking
// isExceptionRole, so their order among themselves does not matter.
#include <algorithm>
#include <cstring>
#include <string>

namespace rakupp {
namespace {
struct AncRow { const char* name; const char* extras; };
// sorted by name: looked up by binary search, so no static initialisation runs
const AncRow kAnc[] = {
HEAD

for %extras.keys.sort -> $n {
    say sprintf('    {"%s", "%s"},', $n, %extras{$n}.join(','));
}

say q:to/MID/;
};

const char* const kRoles[] = {
MID

for %isrole.keys.sort -> $n { say sprintf('    "%s",', $n) }

say q:to/TAIL/;
};
}  // namespace

// The comma-separated extras for an X:: name, or nullptr when it has none.
const char* exceptionExtraAncestry(const std::string& n) {
    auto it = std::lower_bound(std::begin(kAnc), std::end(kAnc), n,
        [](const AncRow& r, const std::string& v) { return std::strcmp(r.name, v.c_str()) < 0; });
    return (it != std::end(kAnc) && n == it->name) ? it->extras : nullptr;
}

// True for the X:: names that are ROLES — X::Comp, X::Syntax, X::IO and the
// rest. `.does` and `~~` count them; `.isa` and `.^mro` do not.
bool isExceptionRole(const std::string& n) {
    auto it = std::lower_bound(std::begin(kRoles), std::end(kRoles), n,
        [](const char* r, const std::string& v) { return std::strcmp(r, v.c_str()) < 0; });
    return it != std::end(kRoles) && n == *it;
}
}  // namespace rakupp
TAIL
