#!/usr/bin/env raku
# Bake the CLI's two Raku sub-programs into src/EmbeddedTools.cpp, so a lone
# `rakupp` binary — a copy into a container, a bare rakupp.exe, a package that
# dropped libexec/ — runs the same `rakupp install` and `rakupp doc` as a full
# checkout. Nothing is looked up beside the binary any more.
#
#   rakupp tools/gen-embedded-tools.raku          # rewrite src/EmbeddedTools.cpp
#   rakupp tools/gen-embedded-tools.raku --check  # exit 1 if it is stale
#
# What goes in:
#   tools/install.raku                    as installerSource()
#   tools/doc.raku                        as docToolSource(), with
#   docs/guide/{REFERENCE,FEATURES}.md    spliced into its %DOCS declaration —
#     `rakupp doc` reads the guides, so shipping the script without them would
#     only move the failure one step. The splice happens HERE, at generation
#     time, so the running binary pays nothing to assemble them.
#
# Same shape as tools/js/gen-rt-src.raku: an ARRAY of raw-string chunks under
# 15 KB each, because MSVC caps one string literal at 16 KB. The file is
# checked in rather than generated by CMake — generating it needs a working
# rakupp, which is the thing being built.

my $ROOT = $?FILE.IO.parent.parent;

# ---- the doc tool, with its two guides spliced in ---------------------------
# doc.raku declares `my %DOCS;` and reads it before it goes looking on disk;
# filling that declaration in is the whole of the embed.
constant DOC-END = 'RAKUPP-EMBED-END';

sub doc-source() {
    my $text = $ROOT.add('tools/doc.raku').slurp;
    my $marker = $text.lines.first(*.starts-with('my %DOCS;'));
    die "gen-embedded-tools: tools/doc.raku no longer declares `my %DOCS;`" without $marker;

    my $fill = "my %DOCS;\n";
    for 'REFERENCE.md', 'FEATURES.md' -> $name {
        my $md = $ROOT.add("docs/guide/$name").slurp;
        $md ~= "\n" unless $md.ends-with("\n");
        die "gen-embedded-tools: $name contains a line spelled {DOC-END}"
            if $md.lines.first(* eq DOC-END).defined;
        $fill ~= "%DOCS\{'$name'\} = Q:to/{DOC-END}/;\n" ~ $md ~ DOC-END ~ "\n";
    }
    $text.subst($marker, $fill.chomp)
}

# ---- the C++ blob -----------------------------------------------------------
# Cut on line boundaries so a chunk never ends inside a token; a raw string
# needs no escaping, but a delimiter collision would still end the literal.
sub chunks(Str $s) {
    die "gen-embedded-tools: an embedded tool contains the raw-string delimiter"
        if $s.contains(')RKTOOL"');
    my @out;
    my $pos = 0;
    while $pos < $s.chars {
        my $piece = $s.substr($pos, min(15000, $s.chars - $pos));
        if $pos + $piece.chars < $s.chars {
            my $nl = $piece.rindex("\n");
            $piece = $piece.substr(0, $nl + 1) if $nl.defined && $nl > 0;
        }
        @out.push($piece);
        $pos += $piece.chars;
    }
    @out
}

sub array(Str $name, Str $text) {
    my $out = "static const char* const $name\[] = \{\n";
    $out ~= 'R"RKTOOL(' ~ $_ ~ ')RKTOOL",' ~ "\n" for chunks($text);
    $out ~ "};\n"
}

my $install = $ROOT.add('tools/install.raku').slurp;
my $doc     = doc-source();

my $out = q:to/HEADER/;
// GENERATED by tools/gen-embedded-tools.raku from tools/install.raku,
// tools/doc.raku and docs/guide/{REFERENCE,FEATURES}.md — DO NOT EDIT
// (t/install/run.raku fails when this file is stale). The two Raku programs
// the CLI dispatches to, baked in so a lone binary carries its own installer
// and its own reference lookup: `rakupp install` no longer needs a script
// beside the executable, on any platform.
//
// CLI-ONLY (CMakeLists.txt): main.cpp is the sole caller, and no `--exe`
// binary can reach either tool, so neither blob rides along in one.
#include "EmbeddedTools.h"
namespace rakupp {
HEADER

$out ~= array('kInstallParts', $install);
$out ~= array('kDocParts', $doc);
$out ~= q:to/FOOTER/;

std::string installerSource() {
    std::string s;
    for (const char* p : kInstallParts) s += p;
    return s;
}
std::string docToolSource() {
    std::string s;
    for (const char* p : kDocParts) s += p;
    return s;
}
} // namespace rakupp
FOOTER

my $target = $ROOT.add('src/EmbeddedTools.cpp');
if @*ARGS[0] eq '--check' {
    if !$target.e || $target.slurp ne $out {
        note "src/EmbeddedTools.cpp is stale — run: rakupp tools/gen-embedded-tools.raku";
        exit 1;
    }
    say "src/EmbeddedTools.cpp is current";
    exit 0;
}
$target.spurt($out);
say "wrote src/EmbeddedTools.cpp: install.raku {$install.chars} chars, "
  ~ "doc.raku+guides {$doc.chars} chars";
