#!/usr/bin/env python3
# Generate src/unicode_blocks_gen.cpp from a PINNED Unicode Blocks.txt (17.0.0),
# NOT from Python's unicodedata (which has no block data and tracks a different
# version). Keeps the block table version-consistent with the rest of the 15.1
# tables in unicode_gen.cpp.  Re-run: python3 tools/gen_unicode_blocks.py
import re

SRC = "tools/ucd/Blocks-17.0.0.txt"
VER = "17.0.0"

blocks = []  # (lo, hi, normalized-name)
for line in open(SRC):
    line = line.split('#', 1)[0].strip()
    if not line:
        continue
    m = re.match(r'([0-9A-Fa-f]+)\.\.([0-9A-Fa-f]+)\s*;\s*(.+)', line)
    if not m:
        continue
    lo, hi, name = int(m.group(1), 16), int(m.group(2), 16), m.group(3).strip()
    norm = re.sub(r'[^a-z0-9]', '', name.lower())  # loose match: lowercase, drop separators
    blocks.append((lo, hi, norm))
blocks.sort()

with open("src/unicode_blocks_gen.cpp", "w") as f:
    f.write(f"// GENERATED by tools/gen_unicode_blocks.py from Unicode {VER} Blocks.txt — do not edit.\n")
    f.write("#include <cstdint>\n#include <cstddef>\n")
    f.write("namespace rakupp {{ namespace ucd {{\n".format())
    f.write("struct BlockEnt { uint32_t lo, hi; const char* name; };\n")
    f.write("extern const BlockEnt BLOCKS[] = {\n")
    for lo, hi, norm in blocks:
        f.write(f'  {{0x{lo:X},0x{hi:X},"{norm}"}},\n')
    f.write("};\n")
    f.write(f"extern const size_t BLOCKS_N = {len(blocks)};\n")
    f.write("}} // namespace rakupp::ucd\n")

print(f"emitted {len(blocks)} blocks -> src/unicode_blocks_gen.cpp")
