#!/usr/bin/env python3
# Generate src/unicode_gb_gen.cpp: UAX #29 Grapheme_Cluster_Break classes as
# (start, end, class) ranges, from the REAL UCD data files (GraphemeBreakProperty
# + emoji-data Extended_Pictographic) rather than a general-category approximation.
# CR/LF/ZWJ/Regional_Indicator/Hangul L/V/T/LV/LVT stay rule-based in C++ (dense,
# stable ranges); everything else — Extend, SpacingMark, Control, Prepend and
# Extended_Pictographic — comes from this table.
import re

CLASSES = {"Extend": 1, "SpacingMark": 2, "Control": 3, "Prepend": 4}
EXTPICT = 5
RULE_BASED = {"CR", "LF", "ZWJ", "Regional_Indicator", "L", "V", "T", "LV", "LVT"}

cp2cls = {}

def add(lo, hi, cls):
    for cp in range(lo, hi + 1):
        cp2cls[cp] = cls

# Grapheme data tracks Unicode 17.0 (what roast's GraphemeBreakTest/emoji-test
# are generated from); the other UCD tables in the repo remain 16.0.
for path, want_extpict in (("tools/ucd/GraphemeBreakProperty-17.0.0.txt", False),
                           ("tools/ucd/emoji-data-17.0.0.txt", True)):
    for line in open(path):
        line = line.split("#")[0].strip()
        if not line:
            continue
        m = re.match(r"([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*(\w+)", line)
        if not m:
            continue
        lo = int(m.group(1), 16)
        hi = int(m.group(2), 16) if m.group(2) else lo
        prop = m.group(3)
        if want_extpict:
            if prop != "Extended_Pictographic":
                continue
            # a codepoint with a real GCB class keeps it; ExtPict only fills GCB=Other
            for cp in range(lo, hi + 1):
                cp2cls.setdefault(cp, EXTPICT)
        else:
            if prop in RULE_BASED:
                continue
            if prop in CLASSES:
                add(lo, hi, CLASSES[prop])

# compress into ranges
ranges = []
for cp in sorted(cp2cls):
    cls = cp2cls[cp]
    if ranges and ranges[-1][1] == cp - 1 and ranges[-1][2] == cls:
        ranges[-1][1] = cp
    else:
        ranges.append([cp, cp, cls])

with open("src/unicode_gb_gen.cpp", "w") as f:
    f.write("// GENERATED by tools/gen_unicode_gb.py from UCD 16.0 "
            "GraphemeBreakProperty + emoji-data. Do not edit.\n")
    f.write("#include <cstdint>\n#include <cstddef>\n")
    f.write("namespace rakupp { namespace ucd {\n")
    f.write("// (start, end, class): 1=Extend 2=SpacingMark 3=Control 4=Prepend 5=Extended_Pictographic\n")
    f.write("extern const uint32_t GBRANGE[] = {\n")
    line = "  "
    for lo, hi, cls in ranges:
        line += f"0x{lo:X},0x{hi:X},{cls},"
        if len(line) > 100:
            f.write(line + "\n"); line = "  "
    f.write(line + "\n};\n")
    f.write(f"extern const size_t GBRANGE_N = {len(ranges)};\n")

    # ---- InCB (Indic_Conjunct_Break) for rule GB9c, from DerivedCoreProperties.
    # 17.0: Unicode 17 extended InCB to Myanmar/Khmer/Balinese/… conjuncts.
    incb = {}
    for line in open("tools/ucd/DerivedCoreProperties-17.0.0.txt"):
        line = line.split("#")[0].strip()
        m = re.match(r"([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*InCB\s*;\s*(\w+)", line)
        if not m:
            continue
        lo = int(m.group(1), 16)
        hi = int(m.group(2), 16) if m.group(2) else lo
        cls = {"Linker": 1, "Consonant": 2, "Extend": 3}[m.group(3)]
        for cp in range(lo, hi + 1):
            incb[cp] = cls
    iranges = []
    for cp in sorted(incb):
        cls = incb[cp]
        if iranges and iranges[-1][1] == cp - 1 and iranges[-1][2] == cls:
            iranges[-1][1] = cp
        else:
            iranges.append([cp, cp, cls])
    f.write("// (start, end, class): 1=InCB Linker 2=InCB Consonant 3=InCB Extend (rule GB9c)\n")
    f.write("extern const uint32_t INCB[] = {\n")
    line = "  "
    for lo, hi, cls in iranges:
        line += f"0x{lo:X},0x{hi:X},{cls},"
        if len(line) > 100:
            f.write(line + "\n"); line = "  "
    f.write(line + "\n};\n")
    f.write(f"extern const size_t INCB_N = {len(iranges)};\n")
    f.write("} }\n")
print(f"gbranges={len(ranges)} incb={len(iranges)}")
