#!/usr/bin/env python3
# Generate src/unicode_norm_gen.cpp: the four normalization tables (CCC, CANON,
# KOMPAT, COMP) parsed DIRECTLY from UnicodeData.txt 17.0 — not from Python's
# unicodedata, whose UCD version lags (3.13 ships 15.1, missing e.g. the
# U+1ACF-era combining marks that roast's nf*-9.t / mass-equality.t exercise).
# Emits the same symbol names the runtime already links; the old copies in
# unicode_gen.cpp are removed by the accompanying splice (see git history).
import re

UD = "tools/ucd/UnicodeData-17.0.0.txt"
DNP = "tools/ucd/DerivedNormalizationProps-17.0.0.txt"

ccc = {}          # cp -> combining class
rawdec = {}       # cp -> (is_compat, [cps])  (one-step decomposition)

for line in open(UD):
    f = line.rstrip("\n").split(";")
    if len(f) < 6:
        continue
    cp = int(f[0], 16)
    if f[3] and f[3] != "0":
        ccc[cp] = int(f[3])
    dec = f[5]
    if dec:
        if dec.startswith("<"):
            parts = dec.split()
            rawdec[cp] = (True, [int(x, 16) for x in parts[1:]])
        else:
            rawdec[cp] = (False, [int(x, 16) for x in dec.split()])

# Full_Composition_Exclusion (covers CompositionExclusions.txt + singletons +
# non-starter decompositions)
fcx = set()
for line in open(DNP):
    line = line.split("#")[0].strip()
    m = re.match(r"([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*Full_Composition_Exclusion", line)
    if m:
        lo = int(m.group(1), 16)
        hi = int(m.group(2), 16) if m.group(2) else lo
        fcx.update(range(lo, hi + 1))

HANGUL_S, HANGUL_END = 0xAC00, 0xD7A3  # composed/decomposed algorithmically in C++

def expand(cp, compat):
    """Recursive full decomposition (canonical only, or canonical+compat)."""
    if HANGUL_S <= cp <= HANGUL_END:
        return [cp]
    e = rawdec.get(cp)
    if e is None or (e[0] and not compat):
        return [cp]
    out = []
    for c in e[1]:
        out.extend(expand(c, compat))
    return out

def reorder(cps):
    """Canonical Ordering Algorithm: stable-sort runs of non-starters by ccc."""
    out = list(cps)
    i = 1
    while i < len(out):
        c = ccc.get(out[i], 0)
        if c and ccc.get(out[i - 1], 0) > c:
            out[i - 1], out[i] = out[i], out[i - 1]
            if i > 1:
                i -= 1
                continue
        i += 1
    return out

canon, kompat, comp = [], [], []
for cp in sorted(rawdec):
    is_compat = rawdec[cp][0]
    if not is_compat:
        full = reorder(expand(cp, False))
        if full != [cp]:
            canon.append((cp, full))
        # composition pair: canonical 2-char decomposition, not fully excluded
        one = rawdec[cp][1]
        if len(one) == 2 and cp not in fcx:
            comp.append((one[0], one[1], cp))
    fullk = reorder(expand(cp, True))
    if fullk != [cp]:
        kompat.append((cp, fullk))

def emit_decomp(f, name, table):
    flat = []
    for cp, ds in table:
        flat.append(cp); flat.append(len(ds)); flat.extend(ds)
    f.write(f"extern const uint32_t {name}[] = {{\n")
    line = "  "
    for v in flat:
        line += f"0x{v:X},"
        if len(line) > 100:
            f.write(line + "\n"); line = "  "
    f.write(line + "\n};\n")
    f.write(f"extern const size_t {name}_N = {len(flat)};\n")

with open("src/unicode_norm_gen.cpp", "w") as f:
    f.write("// GENERATED by tools/gen_unicode_norm.py from UCD 17.0 UnicodeData.txt — do not edit.\n")
    f.write("#include <cstdint>\n#include <cstddef>\n")
    f.write("namespace rakupp { namespace ucd {\n")
    f.write("extern const uint32_t CCC[] = {\n")
    line = "  "
    for cp in sorted(ccc):
        line += f"0x{cp:X},{ccc[cp]},"
        if len(line) > 100:
            f.write(line + "\n"); line = "  "
    f.write(line + "\n};\n")
    f.write(f"extern const size_t CCC_N = {len(ccc) * 2};\n")
    emit_decomp(f, "CANON", canon)
    emit_decomp(f, "KOMPAT", kompat)
    f.write("extern const uint32_t COMP[] = {\n")
    line = "  "
    for a, b, c in sorted(comp):
        line += f"0x{a:X},0x{b:X},0x{c:X},"
        if len(line) > 100:
            f.write(line + "\n"); line = "  "
    f.write(line + "\n};\n")
    f.write(f"extern const size_t COMP_N = {len(comp) * 3};\n")
    f.write("} }\n")
print(f"ccc={len(ccc)} canon={len(canon)} kompat={len(kompat)} comp={len(comp)}")
