#!/usr/bin/env python3
# Generate src/unicode_scripts_gen.cpp — the Unicode Script property, from the
# PINNED 16.0 Scripts.txt.  Re-run: python3 tools/gen_unicode_scripts.py
import re

SRC = "tools/ucd/Scripts-16.0.0.txt"
VER = "16.0.0"

ranges = []  # (lo, hi, ScriptName) — proper case, as in Scripts.txt
for line in open(SRC):
    line = line.split('#', 1)[0].strip()
    if not line:
        continue
    m = re.match(r'([0-9A-Fa-f]+)(?:\.\.([0-9A-Fa-f]+))?\s*;\s*([A-Za-z_]+)', line)
    if not m:
        continue
    lo = int(m.group(1), 16)
    hi = int(m.group(2), 16) if m.group(2) else lo
    ranges.append((lo, hi, m.group(3)))
ranges.sort()

with open("src/unicode_scripts_gen.cpp", "w") as f:
    f.write(f"// GENERATED by tools/gen_unicode_scripts.py from Unicode {VER} Scripts.txt — do not edit.\n")
    f.write("#include <cstdint>\n#include <cstddef>\n")
    f.write("namespace rakupp { namespace ucd {\n")
    f.write("struct ScriptEnt { uint32_t lo, hi; const char* name; };\n")
    f.write("extern const ScriptEnt SCRIPTS[] = {\n")
    for lo, hi, name in ranges:
        f.write(f'  {{0x{lo:X},0x{hi:X},"{name}"}},\n')
    f.write("};\n")
    f.write(f"extern const size_t SCRIPTS_N = {len(ranges)};\n")
    f.write("}} // namespace rakupp::ucd\n")

print(f"emitted {len(ranges)} script ranges -> src/unicode_scripts_gen.cpp")
