#!/usr/bin/env python3
# Generate src/unicode_seq_gen.cpp: the NAMED SEQUENCES `\c[…]` and uniparse
# resolve to more than one codepoint, from the real UCD 17.0 data files:
#   NamedSequences.txt       — LATIN CAPITAL LETTER A WITH MACRON AND GRAVE, …
#   emoji-sequences.txt      — flags, keycaps, modifier sequences ("flag: Canada")
#   emoji-zwj-sequences.txt  — "woman facepalming", "family: man, woman, boy", …
# Names are stored UPPER-CASED (lookup is case-insensitive, as Rakudo's is) and
# sorted for a binary search. A flag is reachable by its bare region name as
# well ("united states" beside "flag: united states"), which is how Rakudo
# resolves it. Where two sources give one name, the first file listed wins.
import re

SOURCES = [
    ("tools/ucd/NamedSequences-17.0.0.txt", "named"),
    ("tools/ucd/emoji-zwj-sequences-17.0.0.txt", "emoji"),
    ("tools/ucd/emoji-sequences-17.0.0.txt", "emoji"),
]

seqs = {}

def add(name, cps):
    key = name.upper()
    if len(cps) > 1 and key not in seqs:
        seqs[key] = cps

for path, kind in SOURCES:
    for line in open(path, encoding="utf-8"):
        line = line.split("#")[0].strip()
        if not line:
            continue
        parts = [p.strip() for p in line.split(";")]
        if kind == "named":
            if len(parts) < 2:
                continue
            name, cps = parts[0], parts[1]
        else:
            if len(parts) < 3 or ".." in parts[0]:
                continue
            cps, name = parts[0], parts[2]
        cplist = [int(c, 16) for c in cps.split()]
        add(name, cplist)
        if kind == "emoji" and name.lower().startswith("flag: "):
            add(name[6:], cplist)

def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

names = sorted(seqs)
flat = []
rows = []
for n in names:
    rows.append((n, len(flat), len(seqs[n])))
    flat.extend(seqs[n])

with open("src/unicode_seq_gen.cpp", "w") as out:
    out.write("// GENERATED by tools/gen_unicode_seq.py from UCD 17.0 NamedSequences +\n")
    out.write("// emoji-sequences + emoji-zwj-sequences. Do not edit.\n")
    out.write("#include <cstdint>\n#include <cstddef>\n")
    out.write("namespace rakupp { namespace ucd {\n")
    out.write("struct SeqEnt { const char* name; uint32_t off, len; };\n")
    out.write("static const uint32_t SEQCPS[] = {\n")
    for i in range(0, len(flat), 12):
        out.write("  " + ",".join("0x%X" % c for c in flat[i:i + 12]) + ",\n")
    out.write("};\n")
    out.write("static const SeqEnt SEQS[] = {\n")
    for n, off, ln in rows:
        out.write("  {%s,%d,%d},\n" % (cstr(n), off, ln))
    out.write("};\n")
    out.write("const SeqEnt* seqTable(size_t* n, const uint32_t** cps) {\n")
    out.write("    *n = sizeof(SEQS) / sizeof(SEQS[0]); *cps = SEQCPS; return SEQS;\n}\n")
    out.write("}} // namespace rakupp::ucd\n")

print("%d named sequences, %d codepoints" % (len(rows), len(flat)))
