#!/usr/bin/env python3
# Generate src/unicode_props_gen.cpp — Unicode binary properties (DerivedCoreProperties
# + PropList) as a prop-indexed range table, from PINNED 16.0 UCD files.
# Re-run: python3 tools/gen_unicode_props.py
import re

FILES = ["tools/ucd/DerivedCoreProperties-17.0.0.txt", "tools/ucd/PropList-17.0.0.txt",
         "tools/ucd/emoji-data-17.0.0.txt"]
VER = "17.0.0"

props = {}   # normalized-name -> list of (lo, hi)
for path in FILES:
    for line in open(path):
        line = line.split('#', 1)[0].strip()
        if not line:
            continue
        m = re.match(r'([0-9A-Fa-f]+)(?:\.\.([0-9A-Fa-f]+))?\s*;\s*([A-Za-z_]+)', line)
        if not m:
            continue
        lo = int(m.group(1), 16)
        hi = int(m.group(2), 16) if m.group(2) else lo
        norm = re.sub(r'[^a-z0-9]', '', m.group(3).lower())
        props.setdefault(norm, []).append((lo, hi))

# Full_Composition_Exclusion is the only binary flag we take from DerivedNormalizationProps
# (the file's other rows carry a value field, e.g. NFC_QC; No — those are enum, not binary).
for line in open("tools/ucd/DerivedNormalizationProps-17.0.0.txt"):
    line = line.split('#', 1)[0].strip()
    if not line:
        continue
    parts = [p.strip() for p in line.split(';')]
    # 2-field rows are pure binary properties; the value-bearing ones (NFC_QC; N …) are enum
    if len(parts) != 2 or parts[1] not in ('Full_Composition_Exclusion', 'Changes_When_NFKC_Casefolded'):
        continue
    lo, _, hi = parts[0].partition('..')
    lo = int(lo, 16); hi = int(hi, 16) if hi else lo
    props.setdefault(re.sub(r'[^a-z0-9]', '', parts[1].lower()), []).append((lo, hi))

# Bidi_Mirrored is UnicodeData.txt field 9 == 'Y' (not in the derived files above).
for line in open("tools/ucd/UnicodeData-17.0.0.txt"):
    f = line.rstrip('\n').split(';')
    if len(f) > 9 and f[9] == 'Y':
        cp = int(f[0], 16)
        props.setdefault('bidimirrored', []).append((cp, cp))

names = sorted(props)
idx = {n: i for i, n in enumerate(names)}

with open("src/unicode_props_gen.cpp", "w") as f:
    f.write(f"// GENERATED by tools/gen_unicode_props.py from Unicode {VER} "
            f"DerivedCoreProperties.txt + PropList.txt — do not edit.\n")
    f.write("#include <cstdint>\n#include <cstddef>\n")
    f.write("namespace rakupp { namespace ucd {\n")
    f.write("extern const char* const PROPNAMES[] = {\n  ")
    f.write(", ".join(f'"{n}"' for n in names))
    f.write("\n};\n")
    f.write(f"extern const size_t PROPNAMES_N = {len(names)};\n")
    f.write("struct PropRange { uint32_t lo, hi; uint16_t prop; };\n")
    f.write("extern const PropRange BINPROPS[] = {\n")
    total = 0
    for n in names:
        for lo, hi in sorted(props[n]):
            f.write(f"  {{0x{lo:X},0x{hi:X},{idx[n]}}},\n")
            total += 1
    f.write("};\n")
    f.write(f"extern const size_t BINPROPS_N = {total};\n")
    f.write("}} // namespace rakupp::ucd\n")

print(f"emitted {len(names)} props, {total} ranges -> src/unicode_props_gen.cpp")
