#!/usr/bin/env python3
# Generate src/unicode_gen.cpp from Python's unicodedata (the Unicode Character Database).
# Tables: combining class, full canonical/compat decomposition, single-step composition pairs.
import unicodedata as u

MAX = 0x110000
ccc = []            # (cp, combining-class)
canon = []          # (cp, [full canonical decomposition])
kompat = []         # (cp, [full compatibility decomposition])
comp = []           # (a, b, composed-cp)  canonical composition pairs

for cp in range(MAX):
    if 0xD800 <= cp <= 0xDFFF:
        continue
    c = chr(cp)
    cc = u.combining(c)
    if cc:
        ccc.append((cp, cc))
    if 0xAC00 <= cp <= 0xD7A3:   # Hangul syllables: decomposed/composed algorithmically in C++
        continue
    nfd = u.normalize('NFD', c)
    if nfd != c:
        canon.append((cp, [ord(x) for x in nfd]))
    nfkd = u.normalize('NFKD', c)
    if nfkd != c:
        kompat.append((cp, [ord(x) for x in nfkd]))
    dec = u.decomposition(c)
    if dec and not dec.startswith('<'):
        parts = [int(x, 16) for x in dec.split()]
        if len(parts) == 2:
            a, b = parts
            if u.normalize('NFC', chr(a) + chr(b)) == c:  # honours composition exclusions
                comp.append((a, b, cp))

def emit_decomp(name, table):
    # flat: cp, len, d0, d1, ...
    flat = []
    for cp, ds in table:
        flat.append(cp); flat.append(len(ds)); flat.extend(ds)
    out = [f"extern const uint32_t {name}[] = {{"]
    line = "  "
    for v in flat:
        line += f"0x{v:X},"
        if len(line) > 100:
            out.append(line); line = "  "
    out.append(line); out.append("};")
    out.append(f"extern const size_t {name}_N = {len(flat)};")
    return "\n".join(out)

with open("src/unicode_gen.cpp", "w") as f:
    f.write("// GENERATED by tools/gen_unicode.py from Unicode %s — do not edit.\n" % u.unidata_version)
    f.write("#include <cstdint>\n#include <cstddef>\n")
    f.write("namespace rakupp { namespace ucd {\n")
    # ccc: cp, class pairs
    f.write("extern const uint32_t CCC[] = {\n")
    line = "  "
    for cp, cc in ccc:
        line += f"0x{cp:X},{cc},"
        if len(line) > 100:
            f.write(line + "\n"); line = "  "
    f.write(line + "\n};\n")
    f.write(f"extern const size_t CCC_N = {len(ccc) * 2};\n")
    f.write(emit_decomp("CANON", canon) + "\n")
    f.write(emit_decomp("KOMPAT", kompat) + "\n")
    # comp: a, b, cp triples
    f.write("extern const uint32_t COMP[] = {\n")
    line = "  "
    for a, b, cp in comp:
        line += f"0x{a:X},0x{b:X},0x{cp:X},"
        if len(line) > 100:
            f.write(line + "\n"); line = "  "
    f.write(line + "\n};\n")
    f.write(f"extern const size_t COMP_N = {len(comp) * 3};\n")
    f.write("} }\n")

print(f"ccc={len(ccc)} canon={len(canon)} kompat={len(kompat)} comp={len(comp)}")

# ---- names + numeric values (separate file) ----
from fractions import Fraction
names = []   # (NAME, cp) for non-algorithmic named chars
numv = []    # (cp, numerator, denominator)
ALG = ('CJK UNIFIED', 'CJK COMPATIBILITY IDEOGRAPH', 'HANGUL SYLLABLE',
       'TANGUT IDEOGRAPH', 'EGYPTIAN HIEROGLYPH', 'NUSHU CHARACTER', 'KHITAN SMALL SCRIPT')
for cp in range(0x110000):
    if 0xD800 <= cp <= 0xDFFF:
        continue
    c = chr(cp)
    try:
        nm = u.name(c)
        if not nm.startswith(ALG):
            names.append((nm, cp))
    except ValueError:
        pass
    val = u.numeric(c, None)
    if val is not None:
        fr = Fraction(val).limit_denominator(1000000)
        numv.append((cp, fr.numerator, fr.denominator))
names.sort()  # by name, for binary search

def cstr(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

with open("src/unicode_names.cpp", "w") as f:
    f.write("// GENERATED by tools/gen_unicode.py from Unicode %s — do not edit.\n" % u.unidata_version)
    f.write("#include <cstdint>\n#include <cstddef>\n")
    f.write("namespace rakupp { namespace ucd {\n")
    f.write("struct NameEnt { const char* name; uint32_t cp; };\n")
    f.write("extern const NameEnt NAMES[] = {\n")
    for nm, cp in names:
        f.write(f"  {{{cstr(nm)},0x{cp:X}}},\n")
    f.write("};\n")
    f.write(f"extern const size_t NAMES_N = {len(names)};\n")
    f.write("extern const int64_t NUMV[] = {\n")
    line = "  "
    for cp, n, d in numv:
        line += f"{cp},{n},{d},"
        if len(line) > 100:
            f.write(line + "\n"); line = "  "
    f.write(line + "\n};\n")
    f.write(f"extern const size_t NUMV_N = {len(numv) * 3};\n")
    f.write("} }\n")
print(f"names={len(names)} numv={len(numv)}")

# ---- grapheme-break property (UAX #29), category-derived subset ----
# codes: Extend=1, SpacingMark=2, Control=3  (CR/LF/ZWJ/RI/Hangul/ExtPict handled by rule in C++)
gb = []
for cp in range(0x110000):
    if 0xD800 <= cp <= 0xDFFF:
        continue
    if cp in (0x000D, 0x000A, 0x200D):          # CR/LF/ZWJ by rule
        continue
    if 0x1F1E6 <= cp <= 0x1F1FF:                 # Regional_Indicator by rule
        continue
    if (0x1100 <= cp <= 0x115F or 0x1160 <= cp <= 0x11FF or 0xA960 <= cp <= 0xA97F or
            0xD7B0 <= cp <= 0xD7FF or 0xAC00 <= cp <= 0xD7A3):  # Hangul by rule
        continue
    cat = u.category(chr(cp))
    if cat in ('Mn', 'Me'):
        gb.append((cp, 1))
    elif cat == 'Mc':
        gb.append((cp, 2))
    elif cat in ('Cc', 'Cf', 'Zl', 'Zp'):
        gb.append((cp, 3))

with open("src/unicode_gen.cpp", "a") as f:
    f.write("namespace rakupp { namespace ucd {\n")
    f.write("extern const uint32_t GBPROP[] = {\n")
    line = "  "
    for cp, code in gb:
        line += f"0x{cp:X},{code},"
        if len(line) > 100:
            f.write(line + "\n"); line = "  "
    f.write(line + "\n};\n")
    f.write(f"extern const size_t GBPROP_N = {len(gb) * 2};\n")
    f.write("} }\n")
print(f"gbprop={len(gb)}")

# ---- general category ranges (for regex <:Prop> and .uniprop) ----
CATS = ['Cn','Lu','Ll','Lt','Lm','Lo','Mn','Mc','Me','Nd','Nl','No','Pc','Pd','Ps',
        'Pe','Pi','Pf','Po','Sm','Sc','Sk','So','Zs','Zl','Zp','Cc','Cf','Cs','Co']
CATIDX = {c: i for i, c in enumerate(CATS)}
ranges = []  # (start, end, catidx) for non-Cn runs
run_start = None; run_cat = None; prev = None
def flush_run(end):
    if run_start is not None and run_cat != 0:
        ranges.append((run_start, end, run_cat))
for cp in range(0x110000):
    cat = CATIDX.get(u.category(chr(cp)), 0) if not (0xD800 <= cp <= 0xDFFF) else 0
    if cat != run_cat:
        if run_start is not None: flush_run(prev)
        run_start = cp; run_cat = cat
    prev = cp
flush_run(prev)

with open("src/unicode_gen.cpp", "a") as f:
    f.write("namespace rakupp { namespace ucd {\n")
    f.write("extern const char* const CATNAMES[] = {")
    f.write(",".join('"%s"' % c for c in CATS))
    f.write("};\n")
    f.write("extern const uint32_t GCAT[] = {\n")
    line = "  "
    for s, e, ci in ranges:
        line += f"0x{s:X},0x{e:X},{ci},"
        if len(line) > 100:
            f.write(line + "\n"); line = "  "
    f.write(line + "\n};\n")
    f.write(f"extern const size_t GCAT_N = {len(ranges) * 3};\n")
    f.write("} }\n")
print(f"gcat_ranges={len(ranges)}")
