#!/usr/bin/env python3
# Generate src/unicode_coll_gen.cpp: DUCET collation elements (UCA allkeys.txt
# 17.0) for `unicmp`/`coll`/`.collate`. Tables:
#   COLLCE     — flat uint16 array of (L1,L2,L3) triples
#   COLLSING   — (cp, offset, count) per single-codepoint entry, sorted by cp
#   COLLCONTR  — (cp0, cp1, cp2, offset, count) per contraction (cp2=0 for len 2),
#                sorted by (cp0, longer-first) so a linear probe finds longest match
import re

ce_flat = []      # uint16s
singles = []      # (cp, off, cnt)
contrs = []       # (cp0, cp1, cp2, off, cnt)

def add_ces(ces):
    off = len(ce_flat) // 3
    for l1, l2, l3 in ces:
        ce_flat.extend((l1, l2, l3))
    return off, len(ces)

for line in open("tools/ucd/allkeys-17.0.0.txt"):
    line = line.split("#")[0].strip()
    if not line or line.startswith("@"):
        continue
    m = re.match(r"^([0-9A-F ]+?)\s*;\s*(.+)$", line)
    if not m:
        continue
    cps = [int(x, 16) for x in m.group(1).split()]
    ces = []
    for w in re.findall(r"\[([.*])([0-9A-F]+)\.([0-9A-F]+)\.([0-9A-F]+)\]", m.group(2)):
        ces.append((int(w[1], 16), int(w[2], 16), int(w[3], 16)))
    if not ces:
        continue
    off, cnt = add_ces(ces)
    if len(cps) == 1:
        singles.append((cps[0], off, cnt))
    else:
        c = cps + [0] * (3 - len(cps))
        contrs.append((c[0], c[1], c[2], off, cnt, len(cps)))

singles.sort()
# contractions: group by first cp, longest first within the group
contrs.sort(key=lambda t: (t[0], -t[5], t[1], t[2]))

with open("src/unicode_coll_gen.cpp", "w") as f:
    f.write("// GENERATED by tools/gen_unicode_coll.py from UCA 17.0 allkeys.txt (DUCET). Do not edit.\n")
    f.write("#include <cstdint>\n#include <cstddef>\n")
    f.write("namespace rakupp { namespace ucd {\n")
    f.write("extern const uint16_t COLLCE[] = {\n")
    line = "  "
    for v in ce_flat:
        line += f"{v},"
        if len(line) > 110:
            f.write(line + "\n"); line = "  "
    f.write(line + "\n};\n")
    f.write(f"extern const size_t COLLCE_N = {len(ce_flat)};\n")
    f.write("extern const uint32_t COLLSING[] = {\n")
    line = "  "
    for cp, off, cnt in singles:
        line += f"0x{cp:X},{off},{cnt},"
        if len(line) > 110:
            f.write(line + "\n"); line = "  "
    f.write(line + "\n};\n")
    f.write(f"extern const size_t COLLSING_N = {len(singles)};\n")
    f.write("extern const uint32_t COLLCONTR[] = {\n")
    line = "  "
    for c0, c1, c2, off, cnt, _ in contrs:
        line += f"0x{c0:X},0x{c1:X},0x{c2:X},{off},{cnt},"
        if len(line) > 110:
            f.write(line + "\n"); line = "  "
    f.write(line + "\n};\n")
    f.write(f"extern const size_t COLLCONTR_N = {len(contrs)};\n")
    f.write("} }\n")
print(f"ces={len(ce_flat)//3} singles={len(singles)} contractions={len(contrs)}")
