#!/usr/bin/env python3
# Generate src/unicode_bidi_gen.cpp — the Bidi_Class property, from the PINNED
# 16.0 extracted/DerivedBidiClass.txt.  Re-run: python3 tools/gen_unicode_bidi.py
import re

SRC = "tools/ucd/DerivedBidiClass-17.0.0.txt"
VER = "17.0.0"

ranges = []  # (lo, hi, BidiClass) e.g. "L", "EN", "WS"
for line in open(SRC):
    line = line.split('#', 1)[0].strip()
    if not line:
        continue
    m = re.match(r'([0-9A-Fa-f]+)(?:\.\.([0-9A-Fa-f]+))?\s*;\s*([A-Za-z]+)', line)
    if not m:
        continue
    lo = int(m.group(1), 16)
    hi = int(m.group(2), 16) if m.group(2) else lo
    ranges.append((lo, hi, m.group(3)))
ranges.sort()

with open("src/unicode_bidi_gen.cpp", "w") as f:
    f.write(f"// GENERATED by tools/gen_unicode_bidi.py from Unicode {VER} DerivedBidiClass.txt — do not edit.\n")
    f.write("#include <cstdint>\n#include <cstddef>\n")
    f.write("namespace rakupp { namespace ucd {\n")
    f.write("struct BidiEnt { uint32_t lo, hi; const char* bc; };\n")
    f.write("extern const BidiEnt BIDI[] = {\n")
    for lo, hi, bc in ranges:
        f.write(f'  {{0x{lo:X},0x{hi:X},"{bc}"}},\n')
    f.write("};\n")
    f.write(f"extern const size_t BIDI_N = {len(ranges)};\n")
    f.write("}} // namespace rakupp::ucd\n")

print(f"emitted {len(ranges)} bidi ranges -> src/unicode_bidi_gen.cpp")
