// The `--aot` backend: emit a C++ program that carries this Raku program's
// PARSED AST as data and interprets it at startup, with no lexing or parsing at
// run time.
//
// It used to rebuild the tree by emitting one builder function per node, listing
// each node type's fields by hand. That was quietly LOSSY: a field nobody
// remembered to list simply did not survive, and the binary then ran a program
// subtly unlike the source. `my Int(Str) $n = "42"` compiled into something that
// threw a type error, because VarExpr::declCoerce was not among the fields it
// emitted; `Node::line`, `Stmt::label`, most of Param and nearly all of SubDecl
// went the same way, so diagnostics lost their line numbers too.
//
// Now it serializes through AstSerial, whose writer and reader are ONE visitor
// per node type instantiated twice — a field cannot be saved but not restored,
// because both directions are the same source line. The blob goes in as bytes
// and `deserializeAst` rebuilds it. Nothing here knows what a field is, so
// nothing here can forget one.
#include "Ast.h"
#include "AstSerial.h"
#include "Interpreter.h"
#include <ostream>
#include <sstream>
#include <vector>
#include <string>

namespace rakupp {
namespace {

std::string S(const std::string& s) { // C++ string literal
    std::string o = "\"";
    for (unsigned char c : s) {
        if (c == '\\' || c == '"') { o += '\\'; o += (char)c; }
        else if (c == '\n') o += "\\n";
        else if (c == '\t') o += "\\t";
        else if (c == '\r') o += "\\r";
        else if (c < 0x20 || c >= 0x7f) { char b[8]; snprintf(b, sizeof b, "\\%03o", c); o += b; }
        else o += (char)c;
    }
    o += "\"";
    return o;
}

} // namespace

// A byte array rather than one enormous string literal: MSVC caps a literal at
// 64 KB and a real module's AST goes well past that.
static void emitBytes(std::ostream& out, const std::string& sym, const std::string& data) {
    out << "static const unsigned char " << sym << "[] = {";
    for (size_t i = 0; i < data.size(); i++) {
        if (i % 20 == 0) out << "\n  ";
        out << (unsigned)(unsigned char)data[i] << ",";
    }
    out << "\n};\n";
}

void emitModuleTable(const std::vector<BundledModule>& mods, std::ostream& decls,
                     std::ostream& calls, bool withSources) {
    if (mods.empty()) return;
    decls << "\n// Modules compiled into this binary: their parsed ASTs travel as bytes,\n"
             "// so the program needs neither their sources nor a precomp cache to run.\n";
    for (size_t i = 0; i < mods.size(); i++) {
        emitBytes(decls, "kMod" + std::to_string(i), mods[i].blob);
        calls << "  rakupp::rakuppRegisterModule(" << S(mods[i].name)
              << ", reinterpret_cast<const char*>(kMod" << i << "), sizeof kMod" << i
              << ", " << S(mods[i].finish) << ");\n";
        // --bundle parses the MAIN program at run time, and that parse scans each
        // `use`d module for the operators it declares. Carry the source for it.
        if (withSources) {
            emitBytes(decls, "kSrc" + std::to_string(i), mods[i].src);
            calls << "  rakupp::rakuppRegisterModuleSource(" << S(mods[i].name)
                  << ", reinterpret_cast<const char*>(kSrc" << i << "), sizeof kSrc" << i << ");\n";
        }
    }
}

void emitAstProgram(const Program& prog, std::ostream& out,
                    const std::string& fileName, const std::string& finish,
                    const std::vector<BundledModule>& mods) {
    std::ostringstream moduleDeclsS, moduleCallsS;
    emitModuleTable(mods, moduleDeclsS, moduleCallsS);
    const std::string moduleDecls = moduleDeclsS.str(), moduleCalls = moduleCallsS.str();
    // Throws AstSerialError if the tree holds something the format cannot carry;
    // main.cpp catches AstEmitError, so translate.
    std::string blob;
    try { blob = serializeAst(prog); }
    catch (const AstSerialError& e) { throw AstEmitError{e.msg}; }

    out << "// Generated by `rakupp --aot`. The Raku program was parsed ahead of time;\n"
           "// its AST travels below as bytes and is rebuilt at startup, so there is no\n"
           "// lexing or parsing at run time.\n"
           "#include \"Ast.h\"\n#include \"AstSerial.h\"\n#include \"Runtime.h\"\n#include \"Interpreter.h\"\n"
           "#include <string>\n#include <vector>\n"
           "#include <cstdlib>\n#include <unistd.h>\n"
           "using namespace rakupp;\n\n";

    emitBytes(out, "kAst", blob);
    out << moduleDecls << "\n";

    out << "int main(int argc, char** argv) {\n"
        << moduleCalls
        << "  Program prog;\n"
           "  deserializeAst(std::string(reinterpret_cast<const char*>(kAst), sizeof kAst), prog);\n"
           "  std::vector<std::string> args; for (int i = 1; i < argc; i++) args.push_back(argv[i]);\n"
           "  std::string exe = argc > 0 ? argv[0] : \"program\"; char rp[4096]; if (realpath(exe.c_str(), rp)) exe = rp;\n"
           "  return rakupp::rakuppRunProgramBigStack(prog, args, " << S(fileName) << ", exe, " << S(finish) << ");\n"
           "}\n";
}

} // namespace rakupp
