// GENERATED by tools/gen-doc-tool-src.raku from tools/doc.raku and
// docs/guide/{REFERENCE,FEATURES}.md — DO NOT EDIT (t/install/run.raku fails
// when this file is stale). The `rakupp doc` program with both guides baked
// into it, so a lone binary can answer a lookup.
//
// The installer's copy is NOT generated: see src/InstallerSrc.cpp, which is
// that program's only copy. This one is, because the guides below are living
// documents with their own source in docs/guide/ — a hand-kept copy would
// drift the moment one is edited.
//
// CLI-ONLY (CMakeLists.txt): main.cpp is the sole caller, so no `--exe`
// binary and no embedder carries a byte of it.
#include "EmbeddedTools.h"
namespace rakupp {
static const char* const kDocParts[] = {
R"RKDOC(#!/usr/bin/env raku
# `rakupp doc SYMBOL ...` — offline lookup of a builtin, method, operator or
# syntax form from the terminal (go doc, perldoc -f, pydoc). A Raku program
# carried INSIDE the binary and dispatched by it, like install.raku.
#
# The content is guide/REFERENCE.md — every entry there was executed on rakupp
# and shows its real output — with FEATURES.md as the second source. Nothing is
# indexed ahead of time: the files are small, and a scan per lookup keeps the
# tool honest about what the docs say TODAY.
#
# Where the docs come from, in order: RAKUPP_DOCS=DIR (an explicit override,
# so a writer can point the tool at a working copy), then the copy baked into
# the binary, then disk. The baked copy is why `rakupp doc` answers from a lone
# executable; %DOCS below is empty in a checkout and filled by
# tools/gen-doc-tool-src.raku on the way into src/DocToolSrc.cpp.
# On disk: a checkout keeps the guides in docs/guide beside tools/, an
# installed layout in share/rakupp/docs.

my %DOCS;
%DOCS{'REFERENCE.md'} = Q:to/RAKUPP-EMBED-END/;
# Raku++ — Language Reference

An exhaustive, example-driven reference for the Raku dialect that **`rakupp`
actually implements**. Unlike [FEATURES.md](FEATURES.md) (thematic inventory) and
[RECIPES.md](RECIPES.md) (task recipes), this document is organised as a *lookup
sheet*: every operator, built-in subroutine, method, and syntactic form, each with
a signature and a runnable example.

**Every example below was executed on `rakupp` and shows its real output** (`# → …`).
Reproduce any of them with:

```sh
./build/rakupp -e 'CODE'
```

Scope note: this reflects the current build, defaulting to **Raku 6.d**. Where
`rakupp` differs from Rakudo or omits something, it is called out inline and
collected in [§14 rakupp-specific notes](#14-rakupp-specific-notes--caveats). The
full machine-extracted inventories (253 subroutines, 736 methods) are in the
[appendices](#appendix-a--all-built-in-subroutines).

---

## Table of contents

1. [Variables, sigils & twigils](#1-variables-sigils--twigils)
2. [Literals & quoting](#2-literals--quoting)
3. [Operators](#3-operators)
4. [Metaoperators](#4-metaoperators)
5. [Built-in subroutines](#5-built-in-subroutines)
6. [Methods by receiver](#6-methods-by-receiver)
7. [Control flow & statement modifiers](#7-control-flow--statement-modifiers)
8. [Routines & signatures](#8-routines--signatures)
9. [Classes, roles, enums, subsets](#9-classes-roles-enums-subsets)
10. [Phasers](#10-phasers)
11. [Regexes & grammars](#11-regexes--grammars)
12. [Special & dynamic variables](#12-special--dynamic-variables)
13. [The type & number tower](#13-the-type--number-tower)
14. [rakupp-specific notes & caveats](#14-rakupp-specific-notes--caveats)
- [Appendix A — all built-in subroutines](#appendix-a--all-built-in-subroutines)
- [Appendix B — all methods](#appendix-b--all-methods)

---

## 1. Variables, sigils & twigils

A sigil marks the *container shape*; a twigil (second character) marks *scope/kind*.

| Sigil | Shape | Example | Result |
|---|---|---|---|
| `$` | scalar (single item) | `my $x = 5; say $x` | `5` |
| `@` | positional (array/list) | `my @a = 1,2,3; say @a[1]` | `2` |
| `%` | associative (hash) | `my %h = a=>1; say %h<a>` | `1` |
| `&` | callable | `my &f = {$_*2}; say f(4)` | `8` |

Twigils:

| Twigil | Meaning | Example |
|---|---|---|
| `$*x` | dynamic (context) variable | `$*PID`, `$*IN`, `$*OUT` |
| `$.x` | public attribute accessor | `has $.x` inside a class |
| `$!x` | private attribute | `has $!x` |
| `$^x` | positional placeholder param | `{ $^a + $^b }` |
| `$?x` | compile-time constant | `$?FILE`, `$?LINE` |
| `$=x` | Pod data | `$=pod` |

Declarators: `my` (lexical), `our` (package), `has` (attribute), `state`
(persistent per-closure), `constant` (compile-time), `temp`/`let` (dynamic
save-restore).

```raku
my  $a = 1;                 # lexical
our $b = 2;                 # package-scoped
state $c = 0; $c++;         # persists across calls
constant K = 42;  say K;    # → 42
```

Binding vs assignment: `=` copies a value into a container; `:=` binds a name
directly to a container (aliasing).

```raku
my $x = 1; my $y := $x; $x = 9; say $y;   # → 9   (aliased)
```

---

## 2. Literals & quoting

### Numbers

```raku
say 42;                 # → 42       Int (arbitrary precision)
say 2 ** 100;           # → 1267650600228229401496703205376
say 0xFF;               # → 255      hex   (also 0o.. octal, 0b.. binary)
say 1_000_000;          # → 1000000  underscore separators
say 3.14;               # → 3.14     Rat (exact rational, not float!)
say (0.1+0.2).raku;     # → 0.3   decimals are Rat: no float error
say 1.5e3;              # → 1500     Num (e-notation opts into float)
say 3+4i;               # → 3+4i     Complex
say 1/3;                # → 0.333333 Rat; (1/3).nude → (1 3)
```

Constants: `pi` / `π`, `e`, `tau` / `τ`, `Inf` / `∞`, `-Inf`, `NaN`.

```raku
say pi;  say e;  say tau;  say Inf;  say NaN;   # → 3.14159… 2.71828… 6.28318… Inf NaN
```

### Strings & quoting forms

| Form | Interpolates? | Example | Result |
|---|---|---|---|
| `'…'` / `q{…}` | no | `q{no $x}` | `no $x` |
| `"…"` / `qq{…}` | yes | `qq{v={1+1}}` | `v=2` |
| `Q{…}` | nothing (fully raw) | `Q{raw \n}` | `raw \n` |
| `<…>` | word list → List | `<a b c>` | `(a b c)` |
| `«…»` / `qw{…}` | word list | `qw{x y z}` | `(x y z)` |
| `q:to/END/` | heredoc | see below | multi-line |

```raku
my @a = 1, 2, 3;
say "sum is {1+2}";      # → sum is 3        block interpolation
say "arr @a[]";          # → arr 1 2 3       interpolate an array with []
my $s = q:to/END/;
    indented heredoc
    second line
    END
say $s.lines.elems;      # → 2   (the /…/ marker's indent is stripped)
```

A heredoc's terminator is delimited like any other quote — `q:to«END»`,
`q:to｢END｣`, `q:to「END」`, `q:to[END]`, `q:to♥END♥` all name `END` — and once
an adverb has been given, whitespace may sit before the delimiter. That is what
makes `q :to ''` legal: it names the **empty** terminator, so a blank line ends
the body.

```raku
my $u = q:to«END»;
    a heredoc, terminator in guillemets
    END
say $u.lines.elems;      # → 1

my $blank = q :to '';
one
two

say $blank.lines.elems;  # → 2
```

> **Note:** the `$(…)` string-contextualiser interpolation form is **not**
> supported inside strings — use `{…}` for any computed interpolation.

---

## 3. Operators

Operators are grouped by precedence tier, **tightest first**. Each entry gives the
operator, a one-line meaning, and a verified example. Word-form operators (`div`,
`eqv`, `Z`, …) are interleaved at their real precedence.

### 3.1 Method / postfix (tightest)

| Op | Meaning | Example → result |
|---|---|---|
| `.meth` | method call | `"hi".uc` → `HI` |
| `.+meth` / `.?meth` | all-candidates / maybe call | `$obj.?maybe` |
| `[ ]` | positional index | `(1,2,3)[1]` → `2` |
| `{ }` | associative index | `%h<k>` / `%h{'k'}` |
| `( )` | invoke | `&f(3)` |
| `++` / `--` | auto-increment / decrement | `my $w=4; say $w++; say $w` → `4`,`5` |

```raku
say (1,2,3)[*-1];         # → 3     *-1 = last index
my %h = a=>1, b=>2;
say %h<a b>;              # → (1 2) hash slice
say <a b c>[1,2];         # → (b c) list slice
```

### 3.2 Exponentiation (right-assoc)

| Op | Meaning | Example → result |
|---|---|---|
| `**` | power | `2 ** 10` → `1024` |

```raku
say 2 ** 0.5;            # → 1.4142135623730951
say 2 ** 3 ** 2;         # → 512   (right-assoc: 2**(3**2))
```

### 3.3 Symbolic unary (prefix)

| Op | Meaning | Example → result |
|---|---|---|
| `-` | numeric negate | `-5` → `-5` |
| `+` | numeric coerce | `+"42"` → `42` |
| `~` | string coerce | `~42` → `42` |
| `?` | Bool coerce | `?1` → `True` |
| `!` | Bool negate | `!1` → `False` |
| `\|` | flatten / slip into args | `f(\|@args)` |
| `+^` `~^` `?^` | bitwise / string / bool NOT | `~0x0F` → `15` |

```raku
say ?1, ' ', !1, ' ', +"42", ' ', ~42, ' ', -5;   # → True False 42 42 -5
```

### 3.4 Multiplicative

| Op | Meaning | Example → result |
|---|---|---|
| `*` | multiply | `6 * 7` → `42` |
| `/` | divide (→ Rat/Num) | `7 / 2` → `3.5` |
| `%` | modulo | `7 % 3` → `1` |
| `%%` | divisible-by (Bool) | `12 %% 3` → `True` |
| `!%%` | not divisible-by | `12 !%% 5` → `True` |
| `div` | integer division | `7 div 2` → `3` |
| `mod` | integer modulo | `7 mod 3` → `1` |
| `gcd` | greatest common divisor | `12 gcd 18` → `6` |
| `lcm` | least common multiple | `4 lcm 6` → `12` |
| `+&` `~&` `?&` | bitwise / buffer / bool AND | `5 +& 6` → `4` |
| `+<` `+>` | bitwise shift left / right | `1 +< 4` → `16`, `255 +> 4` → `15` |
| `o` / `∘` | function composition | `(&a ∘ &b)(x)` |

```raku
say 6 +& 3;   # → 2      bitwise AND
say 1 +< 4;   # → 16     left shift
```

> **Note:** `+<` and `+>` are the integer shifts and both work. The buffer and
> string forms `~<` / `~>` are not implemented here — nor in Rakudo, which
> answers `infix:«~<» not yet implemented` for them.

### 3.5 Additive

| Op | Meaning | Example → result |
|---|---|---|
| `+` | add | `7 + 3` → `10` |
| `-` | subtract | `7 - 3` → `4` |
| `+\|` `~\|` `?\|` | bitwise / string / bool OR | `3 +\| 4` → `7` |
| `+^` `~^` `?^` | bitwise / string / bool XOR | `6 +^ 3` → `5` |

### 3.6 Replication

| Op | Meaning | Example → result |
|---|---|---|
| `x` | string repeat | `'ab' x 3` → `ababab` |
| `xx` | list repeat | `(1,2) xx 2` → `((1 2) (1 2))` |

### 3.7 Concatenation

| Op | Meaning | Example → result |
|---|---|---|
| `~` | string concatenation | `'ab' ~ 'cd'` → `abcd` |

### 3.8 Junctive (autothreading)

| Op | Meaning | Example → result |
|---|---|---|
| `\|` | *any* junction | `5 == (1\|5\|9)` → `any(False, True, False)`, which is `True` in a boolean context |
| `&` | *all* junction | `(1&2&3).so` → `True` |
| `^` | *one* junction | `(1^2)` |

```raku
say 3 == (1 | 3 | 5);    # → any(False, True, False)   the comparison autothreads; it is True in a boolean context
say so 3 == (1 | 3 | 5); # → True
```

### 3.9 Set / bag operators

ASCII and Unicode spellings are equivalent. Combining ops return a `Set`/`Bag`;
relational ops return `Bool`.

| ASCII | Unicode | Meaning | Example → result |
|---|---|---|---|
| `(\|)` | `∪` | union | `(<a b> (\|) <b c>).keys.sort` → `(a b c)` |
| `(&)` | `∩` | intersection | `<a b c> (&) <b c d>` → `Set(b c)` |
| `(-)` | `∖` | difference | `<a b c> (-) <b>` → `Set(a c)` |
| `(^)` | `⊖` | symmetric diff | `<a b> (^) <b c>` → `Set(a c)` |
| `(+)` | `⊎` | baggy sum | `<a b> (+) <a c>` → `Bag(a(2) b c)` |
| `(.)` | `⊍` | baggy multiply | |
| `(elem)` | `∈` | membership | `'a' (elem) <a b c>` → `True` |
| `(!elem)` | `∉` | non-membership | `'z' (!elem) <a b c>` → `True` |
| `(cont)` | `∋` | contains | `<a b> (cont) 'a'` → `True` |
| `(<=)` | `⊆` | subset-or-equal | `<a b> (<=) <a b c>` → `True` |
| `(<)` | `⊂` | strict subset | |
| `(>=)` `(>)` | `⊇` `⊃` | superset / strict | `<a b c> (>) <a b>` → `True` |

### 3.10 Ranges (non-chaining binary)

| Op | Meaning | Example → result |
|---|---|---|
| `..` | inclusive range | `1..5` → `1..5` |
| `..^` | exclude top | `1..^5` → `1..^5`; `.list` → `(1 2 3 4)` |
| `^..` | exclude bottom | `1^..5` → `1^..5`; `.list` → `(2 3 4 5)` |
| `^..^` | exclude both | `1^..^5` → `1^..^5`; `.list` → `(2 3 4)` |
| `^N` | `0..^N` shorthand | `^3` → `^3`; `.list` → `(0 1 2)` |
| `but` / `does` | runtime mixin | `my $v = 5 but "t"; say $v+1` → `6` |

### 3.11 Chaining comparison

Comparisons **chain**: `1 < 2 < 3` means `1 < 2 and 2 < 3`.

| Numeric | String | Meaning | Example → result |
|---|---|---|---|
| `==` | `eq` | equal | `3 == 3.0` → `True` |
| `!=` | `ne` | not equal | `3 != 4` → `True` |
| `<` | `lt` | less | `1 < 2` → `True` |
| `<=` | `le` | ≤ | |
| `>` | `gt` | greater | |
| `>=` | `ge` | ≥ | |
| `<=>` | `leg` | three-way (`Less`/`Same`/`More`) | `3 <=> 5` → `Less` |
| `cmp` | | generic three-way | `'b' cmp 'a'` → `More` |
| `~~` | | smartmatch | `5 ~~ Int` → `True` |
| `===` | | value identity | `5 === 5` → `True` |
| `eqv` | | structural equivalence | `(1,2) eqv (1,2)` → `True` |
| `=:=` | | container identity | `$a =:= $b` |
| `=~=` / `≅` | | approximately-equal | `1 =~= 1.0000000001` |

```raku
say 1 < 2 < 3;             # → True    chained
say 5 ~~ 1..10;            # → True    range smartmatch
say 'foo' ~~ /o+/;         # → ｢oo｣    regex smartmatch (returns Match)
```

### 3.12 Tight-and / tight-or

| Op | Meaning | Example → result |
|---|---|---|
| `&&` | logical and (returns operand) | `5 && 6` → `6` |
| `\|\|` | logical or | `0 \|\| 'x'` → `x` |
| `//` | defined-or | `Nil // 42` → `42` |
| `^^` | logical xor | `True ^^ False` → `True` |
| `min` | numeric minimum | `5 min 2` → `2` |
| `max` | numeric maximum | `5 max 2` → `5` |

```raku
say 0 // 42;    # → 0     // tests definedness, not truth (0 is defined)
say Nil // 42;  # → 42
```

### 3.13 Ternary

| Op | Meaning | Example → result |
|---|---|---|
| `?? !!` | conditional | `5 ?? 'y' !! 'n'` → `y` |

### 3.14 Assignment

| Op | Meaning |
|---|---|
| `=` | assign (copy) |
| `:=` | bind (alias) |
| `+=` `-=` `*=` `/=` `**=` `%=` | compound arithmetic |
| `~=` | compound concat |
| `x=` `xx=` | compound repeat |
| `\|\|=` `&&=` `//=` | compound logical |

```raku
my $n = 10; $n += 5;  say $n;   # → 15
my $s = 'a'; $s ~= 'b'; say $s; # → ab
```

### 3.15 List infix & loose logic

| Op | Meaning | Example → result |
|---|---|---|
| `,` | list constructor | `1,2,3` |
| `=>` | pair constructor | `a => 1` |
| `Z` | zip | `(1,2,3) Z (4,5,6)` → `((1 4) (2 5) (3 6))` |
| `X` | cross | `(1,2) X (3,4)` → `((1 3) (1 4) (2 3) (2 4))` |
| `...` | sequence (lazy) | `1, 3 ... 11` → `(1 3 5 7 9 11)` |
| `...^` | sequence, exclude end | `1 ...^ 5` → `(1 2 3 4)` |
| `and` `or` `not` `xor` | loose logic | `5 and 6` → `6` |
| `andthen` `orelse` | defined-chaining | |

```raku
say 1, 2, 4 ... 32;       # → (1 2 4 8 16 32)   geometric, inferred *2
say 'a' ... 'e';          # → (a b c d e)        string succession
say (10 ... 1);           # → (10 9 … 1)         counts down
```

### 3.16 Feed operators

| Op | Meaning | Example |
|---|---|---|
| `==>` | forward feed (data flows left→right) | see below |
| `<==` | backward feed (right→left) | |

```raku
(1..10) ==> grep(* %% 2) ==> my @evens;
say @evens;               # → [2 4 6 8 10]

my @evens2 <== grep(* %% 2) <== (1..10);
say @evens2;              # → [2 4 6 8 10]
```

---

## 4. Metaoperators

Metaoperators transform an existing operator into a new one.

### Reduce `[OP]`

Fold a list with an infix operator.

```raku
say [+] 1..10;            # → 55
say [*] 1..5;             # → 120
say [~] <a b c>;          # → abc
say [max] 3, 7, 2;        # → 7
say [<=] 1, 2, 3;         # → True    (chained comparison reduced)
say [\+] 1..5;            # → (1 3 6 10 15)   triangular (\) keeps intermediates
```

### Hyper `»OP«` / `>>OP<<`

Apply an operator element-wise; Unicode `»«` or ASCII `>>`/`<<`. Pointy ends
indicate which side may be auto-extended.

```raku
)RKDOC",
R"RKDOC(say (2,3,4) »+» 1;        # → (3 4 5)     scalar broadcast
say (1,2,3) »*» 10;       # → (10 20 30)  (dwim on the scalar side)
say (1,2) »+« (10,20);    # → (11 22)     element-wise
say (1,2,3).map(-*);      # → (-1 -2 -3)  (prefer .map for prefix ops)
```

Hyper method calls: `(1,2,3)>>.abs` calls `.abs` on each element, and
`<a b c>>>.uc` works on a word list too.

### Zip `Z` / Cross `X` with an operator

```raku
say (1,2) Z+ (3,4);       # → (4 6)          zip-with-+
say (1,2) X* (3,4);       # → (3 4 6 8)       cross-with-*
```

### Reverse `R`, Sequential `S`, Cross `X`, Negate `!`

| Meta | Effect | Example → result |
|---|---|---|
| `R` | swap operands | `2 R- 10` → `8` (`10 - 2`) |
| `X` | cross metaop | `Xeqv`, `X~` … |
| `!` | negate a comparison | `!==` already covered by `!=` |

---

## 5. Built-in subroutines

`rakupp` registers **253** built-in subroutines. Below are the commonly used ones
with verified examples, grouped by purpose. The complete alphabetical list is in
[Appendix A](#appendix-a--all-built-in-subroutines).

> **Call-form caveat:** `map({…}, @list)` and `grep({…}, @list)` work here and
> match Rakudo. `sort({…}, @list)` is the one to avoid: it works here and Rakudo
> rejects that spelling as an ambiguous call, so write `@list.sort({…})` for code
> that must run on both.

### Output & I/O

| Sub | Meaning | Example → result |
|---|---|---|
| `say` | `.gist` + newline | `say 42` → `42` |
| `print` | `.Str`, no newline | `print "x"` → `x` |
| `put` | `.Str` + newline | `put "x"` |
| `note` | to `$*ERR` + newline | `note "warn"` |
| `printf` / `sprintf` | C-style format | `sprintf('%05.2f', 3.14159)` → `03.14` |
| `warn` | resumable warning | |
| `die` | throw exception | `die "boom"` |
| `prompt` | read a line with a prompt (no named arguments, as in Rakudo) | `prompt("? ")` |
| `slurp` / `spurt` | read / write whole file | `spurt('f', 'data')` |
| `open` / `close` | file handle | `open('f', :r)` |
| `dir` | directory listing | `dir('.')` |
| `run` / `shell` | run external command | `run(<echo hi>)` |

### Math

| Sub | Example → result |
|---|---|
| `abs` | `abs(-5)` → `5` |
| `sign` | `sign(-3)` → `-1` |
| `sqrt` | `sqrt(2)` → `1.4142135623730951` |
| `floor` `ceiling` `round` | `round(3.14159, 0.01)` → `3.14` |
| `exp` `log` `log10` `log2` | `log10(1000)` → `2.9999999999999996` (binary floating point; `.round` for 3) |
| `sin` `cos` `atan2` … | `atan2(1,1)` → `0.7853981633974483` |
| `min` `max` `minmax` | `minmax(3,1,2)` → `1..3` |
| `sum` | `sum(1..5)` → `15` |
| `is-prime` | `is-prime(7)` → `True` |
| `srand` `rand` | seed / random |

### Strings

| Sub | Example → result |
|---|---|
| `chars` | `chars('café')` → `4` |
| `uc` `lc` `tc` | `tc('foo')` → `Foo` |
| `chr` `ord` `chrs` `ords` | `chr(65)` → `A` |
| `index` `rindex` | `index('abc','b')` → `1` |
| `split` | `split(',', 'a,b,c')` → `(a b c)` |
| `join` | `join('-', 1,2,3)` → `1-2-3` |
| `words` `lines` | `words('a  b c')` → `(a b c)` |
| `uniname` `uniprop` `unival` | Unicode property lookups |

### Lists & sequences

| Sub | Example → result |
|---|---|
| `elems` `end` | `elems(<a b c>)` → `3` |
| `reverse` | `reverse(1,2,3)` → `(3 2 1)` |
| `sort` | `sort(3,1,2)` → `(1 2 3)` |
| `first` | `first(* > 2, 1,2,3,4)` → `3` |
| `grep` | `grep(* %% 2, 1..6)` → `(2 4 6)` |
| `map` | `map(*+1, 1,2,3)` → `(2 3 4)` |
| `reduce` | `reduce(&infix:<+>, 1..4)` → `10` |
| `produce` | `produce(&infix:<+>, 1..4)` → `(1 3 6 10)` |
| `flat` | `flat((1,2),(3,4))` → `(1 2 3 4)` |
| `slip` | `slip((1,2),(3,4))` → `(1 2 3 4)` |
| `roundrobin` | `roundrobin((1,2,3),(4,5,6))` → `((1 4) (2 5) (3 6))` |
| `lazy` `eager` `cache` | force / defer / memoise |
| `push` `pop` `shift` `unshift` `append` `prepend` `splice` | mutators |
| `keys` `values` `kv` `pairs` | from hashes/lists |

### Type / coercion / introspection

| Sub | Meaning | Example → result |
|---|---|---|
| `so` | boolify | `so(5)` → `True` |
| `not` | negate | `not(0)` → `True` |
| `defined` | is defined? | `defined(Nil)` → `False` |
| `item` | scalarise | `item([1,2])` → `[1 2]` |
| `list` | listify | `list(1,2,3)` → `(1 2 3)` |
| `hash` `set` `bag` `mix` | build containers | `bag(<a a b>)` |
| `VAR` `WHAT` | container / type introspection | |
| `EVAL` | evaluate a string as code | `EVAL('1+2')` → `3` |
| `EVALFILE` | evaluate a file as code | `EVALFILE('lib.raku')` |

### Control, concurrency, testing

| Sub | Purpose |
|---|---|
| `exit` `sleep` `sleep-until` | process control |
| `start` `await` `Promise` | async (returns awaitable) |
| `react` `whenever` `supply` `emit` `take` | supplies / reactive |
| `callsame` `callwith` `nextsame` `nextwith` `samewith` `lastcall` | dispatch redirection |
| `gather` / `take` / `take-rw` | lazy generator (`take-rw` takes the writable container, so mutating the sequence's elements writes back) |
| `plan` `ok` `nok` `is` `isnt` `is-deeply` `like` `unlike` `cmp-ok` `dies-ok` `lives-ok` `throws-like` `subtest` `pass` `flunk` `done-testing` … | the **Test** suite (built in) |

```raku
say EVAL('1 + 2');        # → 3
say (gather { take $_ for 1..3 });   # → (1 2 3)
```

---

## 6. Methods by receiver

`rakupp` implements **736** methods (full list in [Appendix B](#appendix-b--all-methods)).
Below are the high-traffic ones grouped by the type they act on.

### On `Str`

```raku
say 'Hello'.chars;               # → 5
say 'Hello'.uc;                  # → HELLO
say 'Hello'.lc;                  # → hello
say 'Hello'.fc;                  # → hello   (fold-case)
say 'hello'.tc;                  # → Hello   (title-case first)
say 'hello world'.tclc;          # → Hello world
say 'hi there'.wordcase;         # → Hi There
say 'Hello'.flip;                # → olleH
say 'Hello'.substr(1,3);         # → ell
say 'a,b,c'.split(',');          # → (a b c)
say '  hi  '.trim;               # → hi
say 'Hello'.contains('ell');     # → True
say 'Hello'.starts-with('He');   # → True
say 'Hello'.ends-with('lo');     # → True
say 'Hello'.index('l');          # → 2
say 'foo'.comb;                  # → (f o o)
say 'a1b2'.comb(/\d/);           # → (1 2)
say 'abc'.trans('a-c' => 'A-C'); # → AbC   ('a-c' is the three characters a, -, c — use 'a'..'c' for a range)
say 'Hello'.subst('l','L',:g);   # → HeLLo
say '2a'.parse-base(16);                 # → 42   (and 42.base(16) → 2A)
say 42.base(2);                  # → 101010
```

### On `Int` / `Rat` / numeric

```raku
say (3.14159).round(0.01);       # → 3.14
say (7/2).Int;                   # → 3
say 10.sqrt;                     # → 3.1622776601683795
say (-5).abs;                    # → 5
say 5.is-prime;                  # → True
say 5.polymod(2, 2);             # → (1 0 1)
say (1/3).numerator;             # → 1
say (1/3).denominator;           # → 3
say (1/3).nude;                  # → (1 3)
say 3.14.floor;                  # → 3
say 3.14.ceiling;                # → 4
say (-3.7).truncate;             # → -3
say 255.chr;                     # → ÿ
say 'A'.ord;                     # → 65
say 42.fmt('%05d');              # → 00042
```

### On `List` / `Array` / `Seq`

```raku
say (1,2,3,4).head(2);           # → (1 2)
say (1,2,3,4).tail(2);           # → (3 4)
say (1,2,3,4,5).skip(2);         # → (3 4 5)
say (1,2,3).reverse;             # → (3 2 1)
say (3,1,2).sort;                # → (1 2 3)
say (3,1,2).sort({ $^b <=> $^a });  # → (3 2 1)  (custom comparator)
say <b a>.sort(*.uc);            # → (a b)        (by key)
say (1,2,3).rotate;              # → (2 3 1)
say (1,2,3).rotate(-1);          # → (3 1 2)
say (1,2,3).elems;               # → 3
say (1,2,3).sum;                 # → 6
say (1,2,3,4).grep(* %% 2);      # → (2 4)
say (1,2,3).map(* + 1);          # → (2 3 4)
say (1,2,3,4).first(* > 2);      # → 3
say (1..6).classify(* %% 2).sort;# → (False => [1 3 5] True => [2 4 6])
say (1..5).rotor(2);             # → ((1 2) (3 4))
say (1,2,2,3,3).unique;          # → (1 2 3)
say (1,1,2,2).squish;            # → (1 2)
say (1,2,3).roll(2);             # → e.g. (1 3)   (with replacement)
say (1,2,3).pick(2);             # → e.g. (2 3)   (without replacement)
say (1,2,3).permutations.elems;  # → 6
say (1,2,3).combinations.elems;  # → 8
say (1,2,3).kv;                  # → (0 1 1 2 2 3)
say (1,2,3).join(',');           # → 1,2,3
```

### On `Hash` / `Map`

```raku
my %h = a => 1, b => 2;
say %h.keys.sort;                # → (a b)
say %h.values.sort;              # → (1 2)
say %h.pairs.sort;               # → (a => 1 b => 2)
say %h.kv.sort;                  # → (1 2 a b)
say %h.elems;                    # → 2
say %h.invert.sort;              # → (1 => a 2 => b)
say %h<a>;                       # → 1        (<> literal-key subscript)
say %h{'a'};                     # → 1        ({} expression-key subscript)
say %h.map(*.value).sort;        # → (1 2)
```

### Introspection & coercion (universal)

```raku
say 5.WHAT;                      # → (Int)
say 5.^name;                     # → Int
say 5.WHICH;                     # → Int|5      (value identity)
say 5.HOW.^name;                 # → Perl6::Metamodel::ClassHOW
say 5.Str; say 5.Int; say 5.Num; say 5.Rat;   # → 5 5 5 5 (one per line)
say 42.so;                       # → True
say Int.defined;                 # → False    (type object is undefined)
say 5.defined;                   # → True
say Int.^mro;                    # method-resolution order
```

---

## 7. Control flow & statement modifiers

### Conditionals

```raku
my $maybe = 5;
my $x;
if 5 > 3      { say 'a' } elsif 5 > 4 { say 'b' } else { say 'c' }
unless 0      { say 'runs' }
with   $maybe { say "defined: $_" }          # runs if defined, topicalises
without $x    { say 'undef' }                # inverse of with
# `without … else` compiles here and Rakudo refuses it outright
# ("without does not take else, please rewrite using with") — see §14.
```

### Loops

```raku
for 1..3 { .say }
loop (my $i = 0; $i < 3; $i++) { }           # C-style
my $j = 0; while $j < 3 { $j++ }
$j = 0; repeat { $j++ } while $j < 3;        # test-at-bottom
```

### `given`/`when` (topic dispatch)

```raku
given 3 {
    when 1  { say 'one' }
    when 3  { say 'three' }
    default { say '?' }
}                                            # → three
```

Loop controls: `last`, `next`, `redo`. `when`/`given` controls: `proceed`,
`succeed`.

### Everything is an expression: `do`

```raku
my $r = do given 3 { when 3 { 'three' }; default { '?' } };  say $r; # → three
my @sq = do for 1..3 { $_ * $_ };  say @sq;                          # → [1 4 9]
```

### Statement modifiers (postfix forms)

```raku
my @list = 1, 2, 3;
my $n = 0;
say $_ for 1..3;
say 'yes' if 5 > 3;
$n++ while $n < 10;
.say for @list;
```

---

## 8. Routines & signatures

```raku
sub add($a, $b) { $a + $b }               # positional
sub greet($name = 'world') { "hi $name" } # default value
sub vary(*@rest) { @rest.sum }            # slurpy positional
sub named(:$x, :$y) { $x + $y }           # named params
named(x => 1, y => 2);                     # → 3
sub typed(Int $n --> Str) { "$n" }        # type + return constraint
```

Blocks & lambdas:

```raku
my &sq = -> $x { $x * $x };  say sq(6);   # → 36     pointy block
say { $^a + $^b }(2, 3);                   # → 5      placeholder params
say (-> $x { $x + 1 })(10);                # → 11     immediately invoked
my $c = { $_ * 2 };  say $c(21);           # → 42     $_ is the arg
```

Multi-dispatch:

```raku
multi describe(Int $x) { "int $x" }
multi describe(Str $x) { "str $x" }
say describe(3);      # → int 3
say describe('a');    # → str a
```

`multi` candidates are chosen by arity and type; add a `proto` to declare a shared
signature. `return` exits a routine; `return-rw` returns a writable container.

---

## 9. Classes, roles, enums, subsets

### Classes

```raku
class Point {
    has $.x;                         # public, read-only accessor $.x
    has $.y is rw;                   # writable accessor
    method sum { $.x + $.y }
    method dist { sqrt($.x² + $.y²) }
}
my $p = Point.new(x => 3, y => 4);
say $p.sum;                          # → 7
say $p.x;                            # → 3
```

`has $.name` auto-generates an accessor; `has $!name` is private. `.new` is the
default constructor; override `BUILD`/`TWEAK` to customise. Inheritance: `is
Parent`; introspect with `.^name`, `.^methods`, `.^attributes`, `.^mro`.

### Roles

```raku
role Greet { method hi { "hello" } }
class C does Greet { }
say C.new.hi;                        # → hello
```

### Enums

```raku
enum Color <Red Green Blue>;
say Green;                           # → Green
say Green.value;                     # → 1
```

### Subsets

```raku
subset Even of Int where * %% 2;
my Even $e = 4;  say $e;             # → 4    (assigning an odd value would fail)
```

---

## 10. Phasers

Blocks that run at defined points in a program's life.

| Phaser | Runs |
|---|---|
| `BEGIN` | at compile time |
| `END` | at program end |
| `ENTER` / `LEAVE` | on block entry / exit |
| `FIRST` / `NEXT` / `LAST` | loop: first / each / last iteration |
| `KEEP` / `UNDO` | block exit, on success / failure |
| `CATCH` | exception handling within a block |
| `CONTROL` | control exceptions (warnings, `next`, …) |

```raku
{
    CATCH { default { say "caught: {.message}" } }
    die "boom";
}                                    # → caught: boom
```

`try { … }` wraps a block, traps exceptions, and sets `$!`:

```raku
try { die "boom" };  say $!.message; # → boom
```

---

## 11. Regexes & grammars

### Match & substitution operators

| Form | Meaning |
|---|---|
| `/ … /` or `rx/ … /` | regex literal |
| `m/ … /` | match (returns a `Match`) |
| `m:i/ … /` | `:ignorecase` match |
| `m:s/ … /` | `:sigspace` match (whitespace in the pattern must match whitespace) |
| `m:g/ … /` | `:global` — all matches |
| `m:r/ … /` | `:r`/`:ratchet` — no backtracking; each atom keeps its first match |
| `m:m/ … /` | `:m`/`:ignoremark` — compare base characters, ignoring marks |
| `m:P5/ … /` | `:P5`/`:Perl5` — the pattern is Perl 5 syntax (`( )` groups, `[ ]` classes, `\1` backrefs, `(?i)`/`(?m)`/`(?s)`/`(?x)`, lookaround, `(?<name>…)`, `(?(N)yes\|no)`); works on `s:P5///` and `rx:P5//` too |
| `s/ … / … /` | substitute (in place, on an lvalue) |
| `tr/ … / … /` | transliterate |
| `~~` / `!~~` | apply against a string |

> **The two-letter forms.** `mm//` is a lexer alias this build accepts and
> Rakudo rejects; it attaches no adverb, so it behaves like a plain `m//`.
> **`ms//` is different and worth care: it is Rakudo's `:sigspace` match, and
> this build accepts it without applying `:sigspace`** — the same program
> answers differently on the two engines with no error either side. Write
> `m:s//`, which is correct on both. (`:ignoremark` likewise has its adverbial
> form, `m:m//`, which works here.)

```raku
say 'foo123' ~~ / (\d+) /;    # → ｢123｣      $0 captures the group
say $0;                        # → ｢123｣
say 'hello' ~~ / l+ /;         # → ｢ll｣
)RKDOC",
R"RKDOC(say 'ABC' ~~ m:i/ abc /;       # → ｢ABC｣      case-insensitive
'2023-01-15' ~~ / (\d**4) '-' (\d\d) '-' (\d\d) /;
say "$0/$1/$2";                # → 2023/01/15
my $t = 'Hello World'; $t ~~ s/World/Raku/;  say $t;   # → Hello Raku
say 'a1b2c3' ~~ m:g/ \d /;     # → (｢1｣ ｢2｣ ｢3｣)   :g = global
```

Common regex atoms: `\d \w \s` (+ negated `\D \W \S`), `\h` horizontal and `\v`
vertical whitespace, `\N` any character except a newline, `\c[NAME]` a named or
numbered codepoint, `.` any, `<[abc]>` char class, `<-[abc]>` negated,
`+ * ? **N **N..M` quantifiers, `|` alternation, `( )` capture, `[ ]`
non-capture group, `<name>` subrule, `<?before>`/`<?after>` look-around, anchors
`^ $ « »` and the line anchors `^^` / `$$`. The escapes work inside a character
class too — `<[\w\-]>`, `<[\h]>`. The short control spelling `\cA` is the one
exception: it works in a string literal and is refused inside a regex here,
where Rakudo accepts it (§14).

`|` is not first-match: branches are ranked by longest **declarative prefix**
(the leading literals/classes/quantifiers, up to the first code block or
back-reference), and ranking runs no user code. `||` is the sequential
opt-out — first branch that matches wins.

```raku
say ("abcd" ~~ / [ ab { } cd ] | abc /).Str;   # → abc  (prefix 2 vs 3 — the {} caps branch 1)
say ("ab"   ~~ /  a || ab /).Str;              # → a    (|| takes the first match)
```

Char classes **compose**: members are added with `+` and removed with `-`, and a
`-member` subtracts from the finished set, so it still applies when a leading `-`
has negated the class.

```raku
say ('a-b' ~~ /^ <-space-[\"]>+ $/).so;   # → True    not a space, and not a quote
say ('b'   ~~ /^ <+alpha-[b]> $/).so;     # → False   a letter, except b
say ('42'  ~~ /^ \d+ <|w> $/).so;         # → True    <|w> is a word boundary, either edge
```

A subrule can be captured under a different name, and answers to **both**:

```raku
grammar G { token TOP { <a=b> }; token b { \d+ } }
my $m = G.parse('42');
say $m.hash.keys.sort;    # → (a b)     `<a=b>` fills $<a> AND $<b>
say ~$m<a>, ~$m<b>;       # → 4242
```

Write `<a=.b>` for the alias alone.

### Grammars

```raku
grammar G {
    token TOP  { <num>+ % ',' }
    token num  { \d+ }
}
say G.parse('12,34,56');       # → ｢12,34,56｣   (a Match, or Nil on failure)
```

`grammar` groups named `token`/`rule`/`regex` rules; `.parse` anchors the whole
string, `.subparse` allows a partial match. Add an actions class with
`:actions($obj)` to build a result tree via `make`/`.made`.

---

## 12. Special & dynamic variables

| Variable | Meaning | Example → result |
|---|---|---|
| `$_` | the topic | `.say for 1..3` |
| `$/` | last match | `$0`, `$<name>` index into it |
| `$!` | last exception | `try {…}; say $!.message` |
| `$0 $1 …` | positional captures | from `$/` |
| `@*ARGS` | command-line arguments | |
| `%*ENV` | environment variables | `%*ENV<HOME>` |
| `$*IN $*OUT $*ERR` | standard handles | |
| `$*PID` | process id | `say $*PID > 0` → `True` |
| `$*KERNEL` | kernel info | `$*KERNEL.name` → `darwin` |
| `$*DISTRO` | distribution info | `$*DISTRO.name` → `macos` |
| `$*RAKU` | language object | `$*RAKU.version` → `v6.d` |
| `$*RAKU.compiler` | implementation object | `.name` → `Raku++`, `.backend` → `cpp` |
| `$*CWD` | current directory | |
| `$?FILE $?LINE` | compile-time file/line | |

> `$*OS` does not exist in either engine: `rakupp` answers `(Any)` (see §14),
> Rakudo dies with "Dynamic variable $*OS not found". Use `$*KERNEL` /
> `$*DISTRO`.

> `$*RAKU.compiler.version` reports the **Rakudo era Raku++ is verified
> against** (`v2026.08`), not the Raku++ release — modules gate on
> `$*RAKU.compiler.version < v2023.12` to mean "modern semantics", and answering
> our own `v1.7.0` reads as a pre-2000 Rakudo. The release is on `.release` and
> `.id`; identify the engine with `.name` (`Raku++`) or `.backend` (`cpp`). See
> [faq/differences.md](faq/differences.md).

> `$*RAKU.compiler.build` and `.build-date` are **Raku++ extensions** (Rakudo
> has neither) that identify the individual binary, which `.release`/`.id`
> cannot — every build between two releases reports the same version.
> `.build` names the release and the commit it was built from: `git describe`
> when a tag for that release is reachable (`v3.14.0-74-g9ff47ae` — 74 commits
> past it), and `v3.20.1-ga5b4aa8` when one is not, so the string can never name
> a release the binary is not. `-modified` if the tree had uncommitted changes,
> `unknown` when built from a tarball with no `.git`; `.build-date` is the UTC
> build date.

---

## 13. The type & number tower

Numeric literals promote losslessly and only degrade to floating point when you
opt in (e-notation) or exceed the rational representation.

```
Int  ⊂  Rat  ⊂  FatRat        (exact)
                 ↘
Int → Rat → Num → Complex      (Num = 64-bit float, opt-in via 1e0 etc.)
```

| Type | Literal | Notes |
|---|---|---|
| `Int` | `42`, `0xFF`, `2**100` | arbitrary precision |
| `Rat` | `3.14`, `1/3` | **exact** rational; default for decimals |
| `FatRat` | `1.FatRat / 3` | unbounded-denominator rational |
| `Num` | `1.5e0`, `pi` | IEEE double |
| `Complex` | `3+4i` | |
| `Str` | `"…"` | grapheme-based, Unicode-correct |
| `Bool` | `True` / `False` | an enum; `.Int` → `1`/`0` |
| `Array` `List` `Seq` | `[…]` `(…)` | mutable / immutable / lazy |
| `Hash` `Map` | `{…}` | mutable / immutable assoc |
| `Pair` | `a => 1` | |
| `Range` | `1..5` | |
| `Set` `Bag` `Mix` | `set(…)` `bag(…)` | + mutable `SetHash`/`BagHash`/`MixHash` |
| `Junction` | `1\|2`, `1&2` | autothreading |
| `Nil` / `Any` / `Mu` | the undefined / root types | |

```raku
say 0.1 + 0.2 - 0.3;      # → 0        exact Rat arithmetic (no float error)
say (0.1 + 0.2).raku;     # → 0.3   it's a Rat (`.nude` shows 3/10)
say 0.1e0 + 0.2e0 - 0.3e0;# → 5.551115123125783e-17  opt into Num and the error returns
```

---

## 14. rakupp-specific notes & caveats

Places where the current build differs from Rakudo or has known gaps — verified
while writing this sheet:

- **`$(…)` string interpolation** is unsupported; use `"{ … }"` for computed
  interpolation.
- **An undeclared dynamic variable answers `(Any)`** instead of raising —
  `say $*NO-SUCH-DYN` prints `(Any)` where Rakudo dies with "Dynamic variable
  … not found". A typo in a `$*` name therefore reads as an undefined value.
- **`mm//`** is a non-spec lexer alias this build accepts and Rakudo rejects.
  **`ms//` is worse than that**: Rakudo reads it as the `:sigspace` match and
  this build ignores the adverb, so `'a b' ~~ ms/a b/` matches there and not
  here, silently. Write `m:s//`.
- **`sprintf` accepts an invalid directive.** `sprintf('%y', 1)` prints `%y`
  here; Rakudo dies with "Directive y is not valid in sprintf format".
- **`shell` ignores `:cwd` and `:env`** (`run` honours both), so a `shell`
  given a working directory runs in the caller's instead.
- **`open(:bin)` drops the adverb**: `.slurp` off such a handle answers a `Str`
  here and a `Buf[uint8]` under Rakudo.
- **`throws-like` does not check the exception type**, so a test naming a type
  that does not exist still passes here.
- **An unexpected named argument is accepted.** `sub f($x) {…}; f(1, :nope)`
  runs here; Rakudo dies with "Unexpected named argument 'nope' passed".
- **An unknown subrule matches the empty string.** `<nosuchrule>` and `<same>`
  succeed here without consuming anything; Rakudo raises "No such method".
  `<{ code }>` and `<&name>` are likewise zero-width no-ops here.
- **`\cA` inside a regex is refused** — "Unrecognized backslash sequence" —
  where Rakudo matches. The bracket forms `\c[1]` and `\c[NAME]` work here, and
  `"\cA"` in a string literal works too; it is only the short form in a regex.
- **`without … else`** (and `without … orwith`) compiles here. Rakudo refuses
  it: "without does not take else, please rewrite using with".

---

## Appendix A — all built-in subroutines

The 254 subroutines registered by `Interpreter::registerBuiltins()`
(`src/Builtins.cpp`), alphabetically:

```
!!! ... ??? EVAL EVALFILE RUN-MAIN RUN-MAIN-args-to-capture Slip VAR
WHAT __format__ __qx__ __radix __radix-list __sym-exists __sym-lookup
abs acosec acosech acotan acotanh append asec asech atan2 await bag
bail-out bail_out cache callframe callsame callwith can-ok ceiling
cglobal chars chdir check_routine_sanity chmod chr chrs cis classify
close cmp-ok comb copy cosec cosech cotan cotanh cross dd defined diag
die dies-ok dir does-ok done done-testing done_testing eager elems
emit end eval-dies-ok eval-lives-ok exit exp explicitly-manage expmod
fail fails-like first flat floor flunk full-barrier get getc gist grep
guess_library_name hash index indir is is-approx is-deeply is-prime
isa-ok isnt item join keys kv lastcall lazy lc leave like lines link
list lives-ok log log10 log2 make make-temp-dir make-temp-file map
minmax mix mkdir move nativecast nativesizeof nextcallee nextsame
nextwith nok not note ok open ord ords pack parse-base pass plan pop
prepend print printf proceed prompt push put quietly rakupp-adler32
rakupp-compress rakupp-crc32 rakupp-crypt_random
rakupp-crypt_random_buf rakupp-crypt_random_uniform rakupp-csv-backend
rakupp-digest-backend rakupp-ext-load rakupp-from-csv rakupp-from-json
rakupp-gzslurp rakupp-gzspurt rakupp-hmac rakupp-hmac-hex
rakupp-json-backend rakupp-md5 rakupp-md5-hex rakupp-parse-diagnosis
rakupp-prompt-hidden rakupp-random-backend rakupp-repo-lock
rakupp-repo-unlock rakupp-sha1 rakupp-sha1-hex rakupp-sha224
rakupp-sha224-hex rakupp-sha256 rakupp-sha256-hex rakupp-sha384
rakupp-sha384-hex rakupp-sha512 rakupp-sha512-hex rakupp-to-csv
rakupp-to-json rakupp-uncompress rakupp-zlib-backend react refresh
rename reverse rindex rmdir roots rotor round roundrobin run samemark
samewith say sec sech set shell shift sign signal sink skip skip-rest
sleep sleep-timer sleep-until slip slurp snip snitch so sort splice
split sprintf spurt sqrt srand start subtest succeed sum supply
symlink take take-rw tc throws-like times todo trait_mod:<of> trans
truncate uc unimatch uniname uninames uniparse uniprop uniprops unival
univals unlike unlink unpolar unshift use-ok val values warn whenever
words zip
```

## Appendix B — all methods

The 736 method names dispatched in `Interpreter::methodCall()`
(`src/Builtins.cpp`), alphabetically. Names in `TitleCase` are coercion/type
methods (`.Int`, `.Str`, `.Bag`, `.NFC`); `UPPER-CASE` are introspection/protocol
methods (`.WHAT`, `.AT-POS`, `.BIND-POS`); the rest are ordinary methods.

```
abs absolute accept ACCEPTS accessed acos acosec acosech acosh acot
acotan acotanh acoth acquire acsc acsch act add add-bytes
add_attribute add_method add_role addr after all allocate allof
annotations antipair antipairs any anyof api api-matcher append arch
archetypes archname are arg arity Array array_type ascii asec asech
asin asinh ASSIGN-KEY ASSIGN-POS assuming ast at AT-KEY AT-POS atan
atan2 atanh attribute_table attributes auth auth-matcher authority
backend backtrace Bag Baggy BagHash base base-repeating base_type
basename batch before BIND-KEY BIND-POS bits bless Bool bool-only
bounds break Bridge broken build build-date byte bytes bytes-available
cache CALL-ME Callable callframe can can-install cancel cancelled
candidates cando canonpath caps Capture capture categorize
categorize-list cause ceiling changed Channel chars child chmod chomp
chop chr chrs cis classify classify-list cleanup clear clone close
close-stdin closed code codename codes collate comb combinations
command compiler Complex compose compose_attributes compose_repr
condition config conj connect constraints consume-all-bytes
consume-all-chars consume-available-bytes consume-available-chars
consume-exactly-bytes consume-line-chars container
container_descriptor contains contents copy cos cosec cosech cosh cot
cotan cotanh coth count count-only cpu-arch cpu-cores CREATE created
csc csch cue CWD d Date DateTime day day-fraction day-of-month
day-of-week day-of-year daycount days-in-month days-in-year dd-mm-yyyy
declares_method declaring_package decode decoder deepmap default
defined DEFINITE delayed delete DELETE-KEY DELETE-POS denominator
deref desc dir dir-sep directives dirname dispatcher DISTROnames do
does done dow duckmap DUMP dynamic e eager earlier elems emit empty
encode encode-chars encoder encoding end endian ends-with enums eof
err EVAL exception excludes-max excludes-min exists EXISTS-KEY
EXISTS-POS exitcode exp expmod extension f fail Failure FatRat fc file
files find find_method find_method_qualified finish first
first-date-in-month first-index flat flatmap flip floor flush fmt
formatter freeze from from-json from-list from-posix get get_value
getc getline gist grab grabpairs grep grep-index handled hardware
has_accessor Hash hash head hh-mm-ss hostname hour HOW hyper id im in
in-range in-timezone indent index indices infinite install installed
Instant Int int int-bounds interval invalidate_method_caches invert
invocant IO is-absolute is-deterministic is-empty is-hidden
is-initial-thread is-int is-lazy is-leap-year
is-monotonically-increasing is-prime is-relative is-routine is-setting
IS-WIN is-win is_built is_dispatcher isa isNaN iso88591 item iterator
join json-name julian-date keep kept KERNELnames key keyof keys kill
kv kxxv l lang-version last-date-in-month later latin1 lazy lc level
line lines List list listen live loads local localhost localport lock
log log10 log2 lookup lsb made magnitude managed Map map marshal match
max maxpairs merge message meta method_names method_table methods
migrate min minmax minpairs minute Mix MixHash mixin Mixy mkdir
mm-dd-yyyy mode modified modified-julian-date modifier month move mro
msb multi multi-invocant my name name-for-repository named named_names
narrow native-descriptor need new new-from-daycount new-from-pairs
new_type NFC NFD NFKC NFKD nl-in nl-out nodemap nomark none norm not
note now nude Num numerator Numeric of offset offset-in-hours
offset-in-minutes on-close on-demand one open optional optionality ord
Order ords orig out package Pair pair pairs pairup parameterize
parameters params parent parents parse parse-base parse-names
parsefile parts path path-sep path-spec peer-host peer-port peerhost
peerport perl permutations pick pickpairs pid platform-library-name
plus polar poll polymod pop pos positional posix postmatch pred prefix
prematch prepend preserving print printf produce Promise protect
protect-or-queue-on-recursion publish_boolification_spec
publish_method_cache publish_type_cache pull-one push push-all
push-at-least push-exactly push-until-lazy put quit r race raku rand
Range Rat raw re read read-bits read-ubits readchars readlink readonly
ready Real reals receive recv reduce register REGISTER-DYNAMIC
relative release remove rename repeated repo-chain repository-for-name
repository-for-spec request-garbage-collection resolve restore result
resume rethrow return return-rw returns reverse rindex rmdir
)RKDOC",
R"RKDOC(role_typecheck_list roles roll roots rotate rotor round run run-script
rw rwx rx s samecase samemark samespace say schedule-on sec sech
second self send Seq serial Set set set-line-separators set_api
set_auth set_name set_rw set_shortname set_value set_ver SetHash Setty
shape shell shift short-id short-name shortname sibling sigil sign
signal signature sin sinh sink sink-all skip skip-at-least
skip-at-least-pull-one skip-one slice Slip slurp slurp-rest slurpy
snip snitch so socket-host socket-port sort SPEC spec-version splice
split sprintf spurt sqrt squish stable start starts-with status stderr
stdout stem STORE Str Stringy subbuf subbuf-rw subname subparse subst
subst-mutate substr substr-eq substr-rw succ suffix sum Supply t tail
take tan tanh tap target tc tclc then THREAD throw timedout timezone
to to-json to-posix today toggle total trans tree trim trim-leading
trim-trailing truncate truncate-to truncated-to try-acquire
try_acquire type uc UInt uint unimatch uniname uninames uniparse
uniprop uniprops unique unival univals unlink unlock unmarshal unpack
unpolar unset unshift unwrap usage-name usascii utc utf16 utf32 utf8c8
value values VAR ver Version version version-matcher VMnames volume
vow w wait week week-number week-year weekday-of-month WHAT what
whatever WHERE WHICH WHO whole-second WHY windows1252 wordcase words
wrap write write-bits write-ubits wx x yada year yyyy-mm-dd z zip
```

---

*Generated against the `rakupp` build in this repository; every `# →` output was
produced by running the snippet. If a feature regresses or a caveat is fixed,
update the relevant section — see [FEATURES.md](FEATURES.md) and
[RECIPES.md](RECIPES.md) for the companion docs.*
RAKUPP-EMBED-END
%DOCS{'FEATURES.md'} = Q:to/RAKUPP-EMBED-END/;
# Raku++ — Supported Features

A from-scratch C++17 interpreter for the Raku language, tested against the
[Roast](https://github.com/Raku/roast) suite. This document inventories what
works today, grouped by theme. **~** marks partial support; gaps are noted per section.

See [REFERENCE.md](REFERENCE.md) for an exhaustive lookup sheet (every operator, subroutine, and method with a verified example), [RECIPES.md](RECIPES.md) for recipes of runnable snippets (each verified against `rakupp`), [examples/](../../examples) for complete example programs, and [showcase/](../../showcase) for mid-size showcase programs.

Roast standing: measured per individual test, **~91% of all declared tests pass** (200,220 / ~219,429, counting tests in files that abort before running); on the stricter file bar, **661 / 1,464 fully pass (~45%)** (671 partial, 116 no-TAP, 16 timeout). See [COUNTING.md](../status/COUNTING.md) for how these are defined. (The declared denominator grows as parse fixes land: files that previously died before announcing a plan now declare their real, often larger, dynamic plans.)

## Language versions (6.c / 6.d / 6.e)

Raku++ **defaults to Raku 6.d**, matching Rakudo. The version pragma selects a
revision, and `$*RAKU.version` reflects it:

```sh
rakupp -e 'say $*RAKU.version'                     # v6.d — the default
rakupp -e 'use v6.e.PREVIEW; say $*RAKU.version'   # v6.e
rakupp -e 'use v6.c;         say $*RAKU.version'   # v6.c
```

Three separate runs, deliberately: a version pragma is file-scoped, so all three
in one file would give that file one version — the last one — and Rakudo refuses
such a file outright (`Too late to switch language version`).

**6.e is implemented and gated.** A program without the pragma gets 6.d
behaviour, including for everything 6.e changed: `snip`, `snitch`, `nano`,
`trans`, `.nomark`, `IO::Path.stem`, `Mu.Callable`, `Format` and `q:o` literals
do not exist under 6.d; `sqrt`/`log` of a negative are `NaN` there and `Complex`
under 6.e; `so (5..1)` is `True` there and `False` under 6.e; `%h{**}`, the list
form of `.skip`, `:smartcase`, `comb(SIZE => GAP)`, per-block `@_`, prefix `//`,
`next $v` / `last $v`, `.pm` modules, pseudo-package `Failure`s and a failing
`Grammar.parse` all follow the same rule.

**The revision belongs to the code, not the process.** A module compiled under
`use v6.e.PREVIEW` keeps 6.e semantics when a 6.d program calls it, and a 6.d
mainline does not acquire 6.e semantics by loading a 6.e module. (Rakudo differs
on the second half: `use`-ing a 6.e module there loads `CORE.e` process-wide.)

The full list — every change, run on both engines under both revisions — is
[the 6.e FAQ article](faq/6e.md), and the live scoreboard is
[raku.online/spec/6e](https://raku.online/spec/6e/): **50 of 51 tracked changes
match Rakudo's 6.e**, 46 of them gated on the pragma.

**Deliberately not done:** `RakuAST` (its own campaign); multi-character `.succ`
string ranges, which are 6.e's behaviour under both revisions because 6.d's
cross-product algorithm is not implemented; and the 6.d silent replacement of a
same-named enclosing package, which Rakudo's own warning calls legacy.

## Lexical & Literals
- Int (arbitrary precision / bignum), Num, Rat, **Complex** (`3+4i`); FatRat ~
- Radix `0x` `0o` `0b` `0d` and `:N<…>` (`:16<ff>`, `:36<aZ>`), `_` separators (strictly between digits — `1__0`/`100_` are errors), exponent `1e5`; string→number coercion parses all of these plus Complex (`+"1+2i"`) and the Unicode minus `−`
- Leading-dot fractions `.5`, imaginary `4i`, `∞`/`Inf`/`NaN`, superscripts `²`
- Strings: `'…'` `"…"` `q//` `qq//` `Q//`, heredocs `q:to/END/` (the terminator takes any quote delimiter, `q:to«END»` included)
- Unicode string quotes `‘’ “” ｢｣`, qw `<…>` and guillemet `«…»`
- Escapes `\n \t \x[…] \o[…]` and `\c[NAME]` (Unicode character names)
- Unicode identifiers (combining marks, Latin-Extended, Greek, fullwidth, letterlike)

## Operators
- Arithmetic `+ - * / % %% div mod ** gcd lcm`; prefix `- + ~ ? !`
- Comparison `== != < > <= >= <=> eq ne lt gt le ge cmp leg before after`, chained
- Logical `&& || // ^^ and or xor not`, `andthen` / `orelse`
- Identity / smartmatch `=== !== eqv ~~ !~~` (types, values, ranges, hashes, regex, junctions, object identity)
- Ranges `.. ..^ ^.. ^..^` — integer, string (`'a'..'z'`), and **fractional** (`1.1 .. 3.1`, `-1.5 ..^ 3` step by 1 keeping the fraction); sequence `…` (arithmetic/geometric/closure generators, ascending & descending), junctions `| & ^`
- Reduce `[+]`, zip `Z`, cross `X`, hyper `>>op>>` / `«op»`
- Contextualizers `$( ) @( ) %( ) $[ ]`, ternary `?? !!`, assignment `= := += …`
- Divisibility `%%` and negated `!%%` (both return `Bool`)
- Bitwise / boolean: numeric `+& +| +^`, string `~& ~| ~^`, boolean `?& ?| ?^`
- Function composition `∘` / `o` (`(f ∘ g)(x)` == `f(g(x))`); feed operators `==>` / `<==`
- Compound assignment for word operators (`$x x= 3`, `$n gcd= 12`) and reverse-metaop reduce (`[R~]`, `[R-]`)
- User-defined operators — all six categories: `infix`/`prefix`/`postfix`/`term`/`circumfix`/`postcircumfix` (`sub infix:<…>`, `sub postfix:<!>` → `5!`, `sub circumfix:<⟦ ⟧>`, `sub term:<TAU>`)
- Meta-operators over user-defined operators: `[myop]` reduce, `>>myop<<` hyper, `Z§`/`X§` zip/cross, `$x myop= y` meta-assignment
- Whatever-currying: infix `* + 1`, prefix `~* -* +*`, postcircumfix `*.<key>` `*[i]`, subscript `@a[*-1]` `@a[*]`
- Precedence/associativity traits on custom operators: `is tighter(&infix:<+>)` / `is looser(…)` / `is equiv(…)` / `is assoc<left|right|non>`
- **Gaps:** the word form of a user-defined operator inside a meta-operator (`Zpl`)

## Control Flow
- `if/elsif/else`, `unless`, `while/until`, `for`, C-style `loop`, `repeat`
- `given/when/default`, `with/without`
- Statement modifiers (`if unless while until for given when with`), including chained (`X if A for B`)
- `last/next/redo` (incl. labeled: `LABEL: for … { last LABEL }`), `gather/take` (lazy — an infinite `gather { loop { take … } }` yields on demand; `take-rw` takes the writable container, so mutating the gathered sequence writes back to where the values came from), `do`
- `FIRST` loop phaser (runs once, before the first iteration; `last` inside it breaks the loop)

## Subs, Signatures & Dispatch
- `sub`, `multi`/`proto` dispatch (by type, arity, `where`, literal, `:D`/`:U` smileys)
- Params: positional, named, optional `?`, slurpy `*@`/`*%` (single-argument rule), defaults
- `is rw` / `is copy`, sigilless `\a`, capture `|c`, return-type `-->`, type-capture `::T`
- Sub-signature destructuring: `[$a,$b]` / `($a,$b)` unpack a list arg, `|c($x,$y)` a capture, `*[$a,$b]` a slurpy, and a *named* `@a [$first, *@rest]` (binds `@a` and unpacks it) — with `multi` dispatch on the destructured arity
- Coercion-type containers: `my Int(Str) $n = '42'` coerces the value to the target type
- Anonymous subs, closures, placeholder params `$^a`, sub/block as argument
- Redispatch: `callsame`/`callwith`/`nextsame`/`nextwith`/`samewith`; routine `.wrap`/`.unwrap` (wrapper `callsame`s to the original)
- **Gaps:** `is rw` inside a sub-signature — `sub f(@a [$x is rw, $y])` does not write through

## Objects, Classes, Roles
- `class`/`role`/`grammar`, attributes `has $.x`/`$!x` (+ defaults), accessors
- `method`/`multi method`/`submethod`, `self`, single inheritance `is`, `does`
- `BUILD`, default `.new`, `bless`, enums
- Metamodel: `.^name .^methods .^method_names .^mro .^parents .^roles .^add_method .^find_method .^parameterize` (`Set.^parameterize(Str)` is `Set[Str]`), `.WHAT .WHICH .HOW`
- `augment` reopens a type — user classes **and** built-ins (`augment class Int {…}` reaches `3.method`, and needs `use MONKEY-TYPING` as in Rakudo); `does`/`but` runtime role mixins. `supersede` is not implemented
- Inheritance errors: `class A is A` (self), `class B is Undeclared` → compile-time throws

## Regexes & Grammars
- `/…/`, `m//`, `s///`; char classes `\d \w \s`, `<[…]> <-[…]> <+[…]>`, and **composed** classes that add and subtract members: `<+alpha-[b]>`, `<-space-[\"]>`, `<-[ab]+[b]>` (a `-member` subtracts from the final set, so it applies after a leading `-` negates)
- Unicode property classes: general category short + long (`<:Nd>`/`<:L>`/`<:UppercaseLetter>`), `<:LC>`/`<:Assigned>`, **blocks** `<:InArabic>` (real 17.0 table), and **binary props** `<:Math>`/`<:Alphabetic>`/`<:Soft_Dotted>`/`<:White_Space>`/`<:Other_*>` (DerivedCoreProperties + PropList); negated `<:!…>` and inverted `<-:…>`
- Script classes `<:Latin> <:Syriac> <:Canadian_Aboriginal> …` (real 17.0 Scripts.txt) and `Bidi_Class` `<:bc<L>>`/`<:bc<EN>>`; zero-width property assertions `<?:prop>`/`<!:prop>`
- Anchors `^ $ ^^`, word boundaries `<< >>` / `« »` and either-edge `<|w>`, quantifiers `* + ? ** {n..m}`, alternation `|`/`||` (`|` ranks by longest declarative prefix — true NFA-based LTM, the default since v3.0.0, with `RAKUPP_LTM=0` selecting the legacy probe ranker; see [the book's chapter 23](../book/ch/23-ltm.md); `||` is sequential), **conjunction `A & B` / `A && B`** (all terms match at the same position; the match spans the last term), groups, named captures
- Repeated named captures under a quantifier collate into a list (`@<content>`, `$<x>[1]`)
- **Capture aliases**: numbered `$7=(…)` (sets the capture index, auto-numbering resumes at N+1), named `$<x>=(…)`, list-valued `@<x>=(…)` (each occurrence → an Array element), hash-valued `%<x>=(…)` (matched strings become Hash keys)
- Subrules, grammars (`token`/`rule`/`regex`, `.parse`/`.subparse`/`.parsefile`), `$/ $0…`, actions
- **Subrule aliases** `<alias=rule>` capture under *both* names (`$<alias>` and `$<rule>`); the dotted form `<alias=.rule>` captures under the alias only
- Capture interpolation `"$0/$1"`, callable `.subst` (`.subst(/…/, *.uc)`), non-mutating `S///`
- `Match` accessors: `.from`/`.to`, `.orig`, `.prematch`/`.postmatch`, `.made`/`.ast`
- Match adverbs `:g(lobal) :ex(haustive)` (every match at every position and length) `:x :nth :p :c :i :samecase/:ii :sigspace :samespace/:ss :ignoremark/:m :samemark/:mm`, ordinals `:2nd`, assignment forms `s[…] = … / OP= …`, `$var`/`$^a`/`@a` interpolation in pattern & replacement
- **Gaps:** subtraction directly after a bare property class is read as part of the property NAME, so `<:L-[b]>` matches anything — write `<+:L-[b]>`, which is correct. Backtracking control (`::`) parses but does not cut; Rakudo refuses it outright (`:: not yet implemented`), so neither engine has it

## Unicode (generated from UCD/UCA 17.0 — see [UNICODE.md](UNICODE.md))
- Normalization **NFC / NFD / NFKC / NFKD** (+ Hangul), `Uni`/`NFC`/`NFD` types; `Uni.new(…).Str` is NFC (NFG semantics) — all `nf*-*.t` + `mass-equality.t` pass
- Grapheme clusters (full UAX #29 incl. **GB9c** Indic conjuncts, emoji ZWJ/skin-tones, flags 🇦🇧): `.chars`/`.comb`/`.flip` — `GraphemeBreakTest-*` and `emoji-test.t` (3,825) fully pass
- **UCA collation** — `unicmp`/`coll` from DUCET 17.0 (contractions incl. discontiguous matching, implicit weights): all 8,271 conformance tests pass
- Character names both directions — `\c[NAME]`, `uniname` — incl. control aliases and algorithmic CJK/Tangut/Nushu/**Hangul syllable** names; numeric values `unival`/`univals` as exact Rats, incl. Unihan numerals (`千` = 1000)
- Regex properties: general category (short `<:L>`/`<:Nd>` and long forms), **scripts** `<:Latin>`/`<:Script<Greek>>` (real Scripts.txt), **blocks** `<:InArabic>`, **bidi** `<:bc<L>>`, binary props (`<:Math>`, `<:Soft_Dotted>`, …); negated/inverted `<:!P>`/`<-:P>`

## Data Types & Built-ins
- Array, List/Seq, Hash, Map, Pair, Range, Set/Bag/Mix (+Hash variants), Junction, IO::Path, Proc, Promise
- String: `chars codes uc lc tc fc wordcase samecase index rindex substr split comb subst trans words lines flip trim starts-with~ ends-with~ contains sprintf ords chrs ord chr` (`.trans` supports `a..z` ranges); `undefine($x)` resets a container
- List: `map grep sort reverse join first reduce produce sum min max elems push pop shift unshift splice keys values kv pairs antipairs invert unique repeated squish classify categorize rotor batch permutations combinations rotate flat head tail skip pick roll tree`; `slip(…)` spreads into the enclosing list; `.grep` smartmatches Type/Regex/value; `.head`/`.tail`/`.skip` take `*`/`*-N`/`Inf`; `.min`/`.max` skip undefined elements; list methods on scalars (`5.map`, `42.grep`); `roundrobin`. `.classify`/`.categorize` accept a Callable, Hash, or Array mapper and an `:into(%h)` target; `.tree` builds a nested view (`.tree(N)` depth-limited, `.tree(&c1,&c2,…)` per-level closures); `.flat(:hammer)` flattens through itemised containers too (`[[1,2],[3]].flat(:hammer)` is `(1,2,3)`)
- **Shaped arrays**: `my @a[3]` / `my @a[2;2]` / `Array.new(:shape(2;2))` — fixed-dimension, `.shape`, row-major fill with structural validation (out-of-range or over-full assignment throws `X::OutOfRange`/`X::Assignment::*`), size-changing ops (`push`/`pop`/…) throw `X::IllegalOnFixedDimensionArray`, multi-dim `@a[i;j]` + `AT/EXISTS/ASSIGN-POS(i,j)`, leaf-walking `keys`/`values`/`kv`/`pairs`/`antipairs`/`iterator`/`flat` with index tuples
)RKDOC",
R"RKDOC(- A negative list index does not count from the end — `@a[*-1]` is the from-the-end form. Written literally it is refused at compile time (`@a[-1]`, `@a[0..-1]` → `X::Obsolete`, naming `*-1` as the replacement); reached indirectly (`my $i = -1; @a[$i]`) it is out of range — a Failure, no Python-style wraparound — and an unhandled Failure propagates through further indexing (`@a[$i][0]`). `.AT-POS`/`.ASSIGN-POS`/`.DELETE-POS` throw `X::OutOfRange` on one; `.EXISTS-POS` simply answers `False`
- **Iterator protocol** (S07): `.iterator` on any collection with `pull-one`/`push-all`/`push-exactly`/`skip-at-least`/`count-only`/… and the `IterationEnd` sentinel; **lazy infinite sources** — `^Inf`/`1..Inf` with `.head`/`.skip`/`.grep`/`.first`/`.map` composing lazily (`(^Inf).grep(*.is-prime).head(5)`)
- Hash: `push`/`append` (accumulate values under a key), `kv keys values pairs invert antipairs`
- Math: `abs sqrt floor ceiling round sign exp log log10 log2` + full trig, `polymod`, `base`, `rand` / `.rand`, constants `pi tau e`

## I/O, System, Concurrency
- `open`/FileHandle (`.lines .get .slurp .print .say .put .getc .readchars .flush .close`; `close`/`getc` sub forms), `dir`, `make-temp-file`
- Output buffering: `.out-buffer` reads and (as an l-value) sets how many bytes a handle may hold back — `0`/`False` writes every `print` straight through, `True` restores the default block, an `Int` is the size; also as an adverb at open (`open $f, :w, :!out-buffer`). Setting it flushes what is already pending, as does `.flush`. `$*OUT`/`$*ERR` are unbuffered, as in Rakudo, so a `say` reaches a pipe as it is written; an output-heavy program can buy the block back with `$*OUT.out-buffer = 65536`. A file handle holds back 8 KiB by default, where Rakudo writes through
- `run`/`shell` without `:out` give the child our own stdout, so its output appears as it is produced rather than at its exit; `Proc::Async` `.stdout`/`.stderr` taps are fed each chunk as it is read, and `.lines` taps fire per line
- `IO::Path` tests & stat: `.e .f .d .r .w .x` (real `access()`), `.s` (size), `.z` (empty), `.l` (symlink), `.mode` (octal string), `.modified/.changed/.accessed` (distinct-precision Instants), `.chmod`; filetest-adverb smartmatch `$path.IO ~~ :e/:d/:f/:r/:w/:x/:s/:z/:l`; `chmod`/`unlink`/`mkdir` subs
- `say`/`print`/`put`/`note` (and their method forms) honour a user-overridden dynamic `$*OUT`/`$*ERR` — assigning `my $*OUT = $mock-handle` reroutes output through its `.print`
- `run` → standard `Proc` (`.out.slurp .exitcode .so`; `+$proc` is the exit status); bidirectional `run(:in,:out)` (`.in.spurt` / `.out.slurp`, e.g. piping through `pandoc`); `shell(CMD)` runs `CMD` through `/bin/sh -c` (redirections/pipes work)
- Line-processing: `-n` / `-p` command-line switches (awk/perl line loops over `$*ARGFILES`); `$*IN`/`$*ARGFILES` reading (`.lines .get .words .slurp`, bare `lines()`/`get()`/`words()`)
- **Concurrency (real `std::thread`s + a GIL, CPython-style; blocking ops release the lock: `sleep`/`await` let tasks interleave in time (sleep-sort actually sorts), and external-process waits (`run`/`shell`) run in genuine parallel wall-clock — N concurrent `run('sleep','1')` finish in ~1s, not N s. Optional true CPU parallelism via `RAKUPP_PARALLEL=1`: worker threads run interpreter compute concurrently — per-thread registers/stacks are thread-local, the symbol tables freeze once concurrency engages, and `Lock`/`Semaphore` become real; ~3× on 8 workers, 0 Roast regressions, ThreadSanitizer-clean. Default (flag off) keeps the GIL. `start EXPR` correctly thunks EXPR to the worker):**
  - `Promise` — `start` (kept, or **broken** if the block dies), `await` (blocks, rethrows the cause), manual `Promise.new`/`.keep`/`.break`/`.vow`, `.result`/`.status` (a real `PromiseStatus` enum)/`.cause`/`.Bool`, deferred `.then`, `Promise.anyof`/`.allof` (with `X::Promise::Combinator`), `Proc::Async` (spawns at `.start`, so a fire-and-forget child outlives the program; `.stdout`/`.stderr` taps incl. `.lines`, `bind-stdin` process pipelines, real `.kill`, `:cwd`; `await` returns the finished proc)
  - `Supply` (`from-list` — args are values, `[..]` items stay unflattened / `tap`/`act`/`map`/`grep`/`first`/`do`/`grab`/`unique`/`squish` (incl. `:as`/`:with`)/`head`/`tail`/`skip`/`reverse`/`rotate`/`sort`/`min`/`max` (running extremes, `&mapper`)/`minmax` (running Range)/`produce` (scan)/`reduce`/`zip` (`:with`)/`merge`/`list`/`wait`/…), `Tap.close`, live `Supplier` (`.emit`/`.done`/`.quit`) with combinators as a per-value transform tap-chain (`grep`/`map`/`head`/`first`/`skip`/`unique`/`squish`), a real `react` event loop / `whenever` (incl. `react whenever …`) / `supply { emit … }`
  - Containers: `Proxy.new(:FETCH/:STORE)` (reads/writes run your code), `is rw` / `return-rw`, `$_` rw-aliased to array elements in `for` loops
  - `Channel` (`send`/`receive`/`poll`/`close`/`fail`/`closed`, `X::Channel::*`), `Thread` (`.start`/`.join`, `is-initial-thread`, `$*THREAD`), `Lock`/`Semaphore` (`.protect`/`.acquire`/`.release`), `sleep`
  - `atomicint` containers and the `⚛` operators (`$x⚛++`, `⚛$x`, `$x ⚛= v`) + `atomic-fetch`/`-fetch-inc`/`-fetch-dec`/`-fetch-add`/`atomic-assign` (lock-free by default; correct, and serialised, under `RAKUPP_GIL=1`)
- **NativeCall** ([FFI.md](FFI.md) is the full guide): `sub … is native {*}` / `is native('lib')` / `is native(&lib-sub)` / `is symbol('n')` calls a C function via `dlsym`, marshalled by **`libffi`** — loaded at runtime with `dlopen`, never linked, so the binary keeps no new dependency (`--ffi-info` says what it found; `RAKUPP_FFI=0` turns it off). Arguments and returns are passed at their declared width, so `num32` is a real C `float` and there is no cap on argument count; variadic C functions work by marking where `...` begins with a slurpy (`sub snprintf(Buf, size_t, Str, *@args --> int32)`); callbacks are `ffi_closure`s, so they take typed and floating-point parameters, any arity, and any number of distinct callbacks. The resolved symbol and the prepared call interface are both cached per sub. Where no `libffi` can be loaded, calls fall back to a fixed 8-integer/8-float prototype and anything it cannot express throws rather than computing garbage
  - Scalars: integer/pointer args (`Str`→`char*`, the `int`/`uint`/`size_t`/`bool`/`Pointer` family), floating-point args (`num`/`num32`/`num64`), **and mixed int+float argument lists**, with an integer/pointer/`Str`/float/`void` return. Arguments coerce to their declared type (`sqrt(4)` works); a narrow return (`int32`/`uint16`/…) is truncated and sign/zero-extended to its declared width. Covers all of libc's integer functions and the whole `<math.h>` surface (`strlen`, `getenv`, `sqrt`, `pow`, …)
  - Aggregates: `CArray` (element read/write; in-place mutation copied back), `Buf`/`Blob` buffers filled in place (`recv`/`SSL_read`), `is repr('CStruct')` / `CPointer` classes as arguments and as returns (fields read/written against native memory), `Pointer`/`CArray`/CStruct returns boxed as live handles, `is rw` out-params marshalled as `T*` with copy-back (including the `sqlite3**` shape), plus `nativecast` and `cglobal`
  - Callbacks: a Raku `Callable` passed to C becomes a function pointer via `ffi_closure` — `qsort`/`bsearch` work. Parameters are typed from the `Callable`'s own signature (a declared `Pointer` arrives as a live `Pointer`, a declared `Str` as a `Str`, `num`/`num32` as floats), with any arity, a typed return, and no limit on how many distinct callbacks exist. The callback must still fire *during* the native call (the GIL is held); one arriving on a thread the interpreter never entered is detected and ignored with a warning rather than run. Where `ffi_closure_alloc` is refused by a W^X policy, the old 64-trampoline pool still serves
  - Variadics: a slurpy marks where C's `...` begins — `sub snprintf(Buf, size_t, Str, *@args --> int32) is native {*}` — and each variadic argument is typed from its runtime value under C's default argument promotions. The spelling matches Rakudo's, which reads a trailing slurpy the same way; without it a variadic call is silently wrong on every ABI that passes `...` on the stack, Apple ARM64 included
  - **Gaps**: C structs passed or returned **by value** are unsupported (an 8-byte return can be taken as `int64` and unpacked by hand); callbacks that C stores and fires later from its own thread are detected and ignored, not run; a `CStruct` field that is itself a struct is a pointer, not embedded (no `HAS`). Where no `libffi` can be loaded, `num32`, variadics and more than 8 integer or 8 float arguments all throw `X::NYI` rather than being computed wrongly
- `$*CWD $*EXECUTABLE $*ARGS $*RAKU/$*PERL` (`.compiler.name` = "Raku++", backend "cpp"; `.compiler.version` deliberately reports the **Rakudo era tracked**, `v2026.08`, since modules gate features on it — the Raku++ release is `.release`/`.id`), `$*DISTRO $*KERNEL $*VM $*THREAD $*SCHEDULER`

## Phasers, Modules, Exceptions, Special Vars, Testing
- Phasers: `BEGIN CHECK` (top-level ordering), `INIT END` (program-wide), `ENTER/LEAVE` (block entry/exit), `FIRST` (once per loop), `CATCH`; `BEGIN`/`ENTER` usable in value position. `INIT` runs once before the mainline wherever it is written — nested in a loop, a sub that is never called, or a branch never taken — provided it names no variable from an enclosing scope; one that does still runs in place. `END` is registered where it is written and runs once at program exit, in reverse source order, whatever its depth: in a sub called ten times it still runs once, in the scope of the last entry into the block that holds it, and in a sub that is never called it runs anyway. A module's ENDs take their place at the `use` that loaded it, an EVAL's at the moment it ran
- `state` variables (persistent), modules `use`/`need`/`no`, `use lib <expr>`, sub hoisting, `EVAL`
- **`use Data::Native`** — five tags (`json csv digest zlib random`), thirty-two names, answered by the compiler from its own built-ins with nothing installed and nothing loaded; the same line loads a portable distribution on any other engine, and `*-backend()` says which answered. See [DATA-NATIVE.md](DATA-NATIVE.md)
- **POD DOM**: `$=pod` / `@=pod` as `Pod::Block` objects (`Pod::Block::Named`/`::Para`/`::Code`/`::Comment`, `Pod::Heading`, `Pod::Item`) with `.name`/`.contents`/`.level` — delimited/paragraph/abbreviated blocks, nesting, indent-based code blocks; plus `$=finish`
- Exceptions: `die`/`try`/`CATCH`, `throws-like`, `X::*` (partial), resumable via `.resume` inside a `CATCH`; `fail`/`Failure.new` carry an exception (`.exception`), report undefined for `//`
- Special vars: `$_ $/ $! @*ARGS $?LINE $?FILE`
- Test API: `plan ok nok is isnt is-deeply like unlike cmp-ok isa-ok is-approx dies-ok lives-ok throws-like eval-lives-ok subtest skip todo pass flunk diag done-testing "plan skip-all"`
RAKUPP-EMBED-END

# The on-disk search, used only by a build with no baked copy.
sub docs-dir() {
    my $here = $*PROGRAM.IO.resolve.parent;
    for $here.parent.add('docs/guide'), $here.parent.parent.add('share/rakupp/docs') -> $d {
        return $d if $d.add('REFERENCE.md').e;
    }
    return IO::Path;
}

# One guide's text, or Nil if this build has neither a baked copy nor a file.
sub doc-text(Str $name) {
    if %*ENV<RAKUPP_DOCS> -> $over {        # set and non-empty: it decides alone
        my $f = $over.IO.add($name);
        return $f.e ?? $f.slurp !! Nil;
    }
    return %DOCS{$name} if %DOCS{$name}:exists;
    my $dir = docs-dir();
    return Nil unless $dir.defined;
    my $f = $dir.add($name);
    $f.e ?? $f.slurp !! Nil
}

# One hit: where it is (heading trail), and the line itself.
class Hit { has $.file; has @.trail; has $.line; has $.kind }

# Scan one markdown file for lines that mention the symbol: table rows whose
# FIRST cell names it (those carry the meaning column), lines of code blocks,
# and prose lines with it in inline code. Word-bounded for identifiers; a
# symbol made of punctuation (`»`, `<=>`, `Z`) matches as a substring.
sub scan(Str $name, Str $text, Str $sym) {
    my @hits;
    my @trail;            # the current ## / ### heading path
    my $in-code = False;
    my $wordy = so $sym ~~ /^ <[\w\-]>+ $/;
    my $re = $wordy ?? rx/ <|w> $sym <|w> / !! rx/ $sym /;
    for $text.lines.kv -> $n, $l {
        if $l ~~ /^ '```' / { $in-code = !$in-code; next }
        if !$in-code && $l ~~ /^ ('#'+) \s+ (.*) $/ {
            my $level = $0.chars;
            next if $level == 1;                 # the file title is not a location
            @trail = @trail[^($level - 2)];
            @trail[$level - 2] = ~$1;
            next;
        }
        next unless $l ~~ $re;
        my $kind;
        if $l ~~ /^ \s* '|' / {
            # a table row: the symbol must be in the first cell to count as
            # an entry (a mention in the "example" column is not one)
            my $first = $l.split('|')[1] // '';
            next unless $first ~~ $re;
            next if $first ~~ /^ \s* '-'+ \s* $/;   # the header separator
            $kind = 'table';
        }
        elsif $in-code { $kind = 'code' }
        elsif $l ~~ / '`' <-[`]>* $sym <-[`]>* '`' / { $kind = 'prose' }
        else { next }
        @hits.push: Hit.new(:file($name), :trail(@trail.grep(*.defined).Array), :line($l.trim), :$kind);
    }
    @hits
}

sub show(@hits, Int $max) {
    my $last = '';
    my $shown = 0;
    for @hits -> $h {
        last if $shown >= $max;
        my $where = $h.file ~ ' › ' ~ $h.trail.join(' › ');
        if $where ne $last { say ($shown ?? "\n" !! '') ~ $where; $last = $where }
        say '    ' ~ $h.line;
        $shown++;
    }
    if @hits > $max { say "\n… {@hits - $max} more (--all shows every hit)" }
}

# `rakupp doc :i` used to print the usage instead of the entry. A Raku adverb is
# exactly the kind of thing a reader reaches for `doc` to explain, but MAIN's
# argument parser reads a leading colon as a NAMED argument, finds no `:i`
# parameter, and gives up on the whole dispatch. Protecting the token here and
# unwrapping it in MAIN costs two lines and keeps every other spelling as it was.
# (A user-defined `ARGS-TO-CAPTURE` would be the tidy way; Rakudo honours one and
# Raku++ ignores it, so this survives both.)
constant ADVERB = "\0adverb\0";
@*ARGS = @*ARGS.map({ .starts-with(':') ?? ADVERB ~ $_ !! $_ });

#| Look a Raku symbol up in the language reference: a builtin, a method, an operator, a syntax form
sub MAIN(
    *@symbols,          #= what to look up: trim, .comb, Z, <=>, gather, MAIN …
    Bool :$all,         #= every hit, not the first dozen
    Bool :$code,        #= code examples only (skip the tables and the prose)
) {
    unless @symbols { note "Usage: rakupp doc SYMBOL ...   (e.g. rakupp doc trim, rakupp doc '<=>', rakupp doc gather)"; exit 2 }
)RKDOC",
R"RKDOC(    my %text = ('REFERENCE.md', 'FEATURES.md').map({ $_ => doc-text($_) }).grep(*.value.defined).Hash;
    unless %text {
        note "rakupp doc: cannot find REFERENCE.md (this binary carries no baked copy, and none is on disk; RAKUPP_DOCS=DIR overrides)";
        exit 1;
    }
    my $missing = 0;
    for @symbols.map(*.subst(/^ $(ADVERB) /, '')) -> $raw {
        my $sym = $raw.subst(/^ '.' /, '');          # `.trim` is the method spelling of `trim`
        my @hits;
        for 'REFERENCE.md', 'FEATURES.md' -> $name {
            next unless %text{$name}:exists;
            @hits.append: scan($name, %text{$name}, $sym);
        }
        @hits .= grep(*.kind eq 'code') if $code;
        # tables first (they carry the meaning), then code, then prose —
        # REFERENCE before FEATURES within each
        my %rank = table => 0, code => 1, prose => 2;
        @hits = @hits.sort({ %rank{.kind}, .file ne 'REFERENCE.md' });
        if !@hits {
            say "$sym: nothing in REFERENCE.md or FEATURES.md";
            $missing++;
            next;
        }
        say "== $sym  ({@hits.elems} hit{@hits == 1 ?? '' !! 's'})" if @symbols > 1;
        show(@hits, $all ?? @hits.elems !! 12);
        say '' if @symbols > 1;
    }
    exit($missing == @symbols ?? 1 !! 0);
}
)RKDOC",
};
std::string docToolSource() {
    std::string s;
    for (const char* p : kDocParts) s += p;
    return s;
}
} // namespace rakupp
