#pragma once
// The Raku programs `rakupp install` and `rakupp doc` dispatch to, carried
// inside the CLI instead of beside it (EmbeddedTools.cpp, generated by
// tools/gen-embedded-tools.raku). A binary on its own — copied into a
// container, unpacked as a bare rakupp.exe, installed by a route that dropped
// libexec/ — runs the same tools as a checkout.
//
// CLI-only: main.cpp is the only caller, and CMakeLists.txt keeps the
// translation unit out of rakupp_rt so no `--exe` binary carries the blobs.
#include <string>

namespace rakupp {

std::string installerSource();  // tools/install.raku
std::string docToolSource();    // tools/doc.raku, with the two guides spliced in

} // namespace rakupp
