#include "Runtime.h"
#include "Codegen.h"
#include "Lexer.h"
#include "Parser.h"
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>
#include <unistd.h>

using namespace rakupp;

// ---- helpers for the compile modes (--bundle / --aot / --exe) ----------

// Wrap a string in single quotes for the shell (escaping embedded quotes).
static std::string shq(const std::string& s) {
    std::string out = "'";
    for (char c : s) { if (c == '\'') out += "'\\''"; else out += c; }
    out += "'";
    return out;
}

// Emit a C++ string literal for `s` (used for the embedded program name).
static std::string cppstr(const std::string& s) {
    std::string out = "\"";
    for (unsigned char c : s) {
        if (c == '\\' || c == '"') { out += '\\'; out += (char)c; }
        else if (c == '\n') out += "\\n";
        else if (c < 0x20) { char b[8]; snprintf(b, sizeof b, "\\x%02x", c); out += b; }
        else out += (char)c;
    }
    out += "\"";
    return out;
}

static std::string dirOf(const std::string& path) {
    auto p = path.find_last_of('/');
    return p == std::string::npos ? "." : path.substr(0, p);
}
static std::string baseOf(const std::string& path) {
    auto p = path.find_last_of('/');
    return p == std::string::npos ? path : path.substr(p + 1);
}

// Default output path for a compiled program: the source name minus a Raku
// extension, or `a.out` for `-e` code.
static std::string defaultOut(const std::string& srcName) {
    if (srcName == "-e") return "a.out";
    for (const char* ext : {".rakumod", ".raku", ".p6", ".pl6"}) {
        size_t n = std::string(ext).size();
        if (srcName.size() > n && srcName.compare(srcName.size() - n, n, ext) == 0)
            return srcName.substr(0, srcName.size() - n);
    }
    return srcName + ".out";
}

// Bundle a Raku program into a standalone native executable: generate a
// small C++ stub that embeds the program source and calls the runtime, then
// link it against librakupp_rt.a (statically, so the result needs no rakupp).
static int compileToExe(const std::string& src, const std::string& srcName, std::string outPath, const std::string& selfExe) {
    if (outPath.empty()) outPath = defaultOut(srcName);

    // The runtime static library sits next to this rakupp binary.
    std::string lib = dirOf(selfExe) + "/librakupp_rt.a";
    if (std::ifstream(lib).good() == false) {
        std::cerr << "Cannot find runtime library: " << lib
                  << "\n(build rakupp first: cmake --build build)\n";
        return 5;
    }

    // Generate the stub. The program source is embedded as a raw byte array so
    // that any content (quotes, delimiters, binary) round-trips exactly.
    std::string stubPath = outPath + ".rakupp.stub.cpp";
    {
        std::ofstream stub(stubPath);
        if (!stub) { std::cerr << "Cannot write " << stubPath << "\n"; return 5; }
        stub << "// Generated by `rakupp --bundle`. Embeds a Raku program and runs it\n"
                "// via the linked-in Raku++ runtime.\n"
                "#include <string>\n#include <vector>\n#include <cstdlib>\n"
                "namespace rakupp { int rakuppRunBigStack(const std::string&, std::vector<std::string>,"
                " const std::string&, const std::string&); }\n";
        stub << "static const unsigned char SRC[] = {";
        for (size_t i = 0; i < src.size(); i++) { if (i) stub << ","; stub << (int)(unsigned char)src[i]; }
        if (src.empty()) stub << "0"; // avoid zero-size array; length tracked separately
        stub << "};\n";
        stub << "static const unsigned long SRC_LEN = " << src.size() << "UL;\n";
        stub << "int main(int argc, char** argv) {\n"
                "  std::string src(reinterpret_cast<const char*>(SRC), SRC_LEN);\n"
                "  std::vector<std::string> args; for (int i = 1; i < argc; i++) args.push_back(argv[i]);\n"
                "  std::string exe = argc > 0 ? argv[0] : \"program\";\n"
                "  char rp[4096]; if (realpath(exe.c_str(), rp)) exe = rp;\n"
                "  return rakupp::rakuppRunBigStack(src, args, " << cppstr(baseOf(srcName)) << ", exe);\n"
                "}\n";
    }

    const char* cxxEnv = std::getenv("CXX");
    std::string cxx = cxxEnv && *cxxEnv ? cxxEnv : "c++";
    std::string cmd = cxx + " -std=c++17 -O2 -pthread -Wl,-w " + shq(stubPath) + " " + shq(lib)
                    + " -o " + shq(outPath);
    int rc = std::system(cmd.c_str());
    std::remove(stubPath.c_str());
    if (rc != 0) { std::cerr << "Compilation failed (compiler exit " << rc << ")\n"; return 5; }
    std::cerr << "Compiled " << srcName << " -> " << outPath << "\n";
    return 0;
}

// Fully compile a Raku program to a native executable by transpiling its AST to
// C++ (no interpreter embedded) and linking against the runtime library. Falls
// back with a clear message if the program uses an unsupported construct.
static int compileNative(const std::string& src, const std::string& srcName, std::string outPath, const std::string& selfExe) {
    if (outPath.empty()) outPath = defaultOut(srcName);

    std::string cpp;
    try {
        Lexer lexer(src);
        Parser parser(lexer.tokenize());
        Program prog = parser.parseProgram();
        cpp = transpileToCpp(prog);
    } catch (const ParseError& e) {
        std::cerr << "===SORRY!=== Parse error at line " << e.line << ": " << e.what() << "\n";
        return 2;
    } catch (const CodegenError& e) {
        // Any construct outside the native subset: fall back to AOT bundling so
        // `--exe` still produces a correct binary for the full language.
        std::cerr << "note: " << e.msg << " — not yet natively compiled; "
                     "bundling the whole program with the interpreter instead.\n";
        return compileToExe(src, srcName, outPath, selfExe);
    }

    std::string dir = dirOf(selfExe);
    std::string lib = dir + "/librakupp_rt.a";
    std::string inc = dir + "/../src";
    if (std::ifstream(lib).good() == false) {
        std::cerr << "Cannot find runtime library: " << lib << "\n(build rakupp first)\n";
        return 5;
    }

    std::string genPath = outPath + ".rakupp.gen.cpp";
    { std::ofstream g(genPath); if (!g) { std::cerr << "Cannot write " << genPath << "\n"; return 5; } g << cpp; }

    const char* cxxEnv = std::getenv("CXX");
    std::string cxx = cxxEnv && *cxxEnv ? cxxEnv : "c++";
    std::string cmd = cxx + " -std=c++17 -O2 -w -pthread -Wl,-w -I " + shq(inc) + " "
                    + shq(genPath) + " " + shq(lib) + " -o " + shq(outPath);
    int rc = std::system(cmd.c_str());
    if (!std::getenv("RAKUPP_KEEPGEN")) std::remove(genPath.c_str());
    if (rc != 0) { std::cerr << "Compilation failed (compiler exit " << rc << ")\n"; return 5; }
    std::cerr << "Compiled (native) " << srcName << " -> " << outPath << "\n";
    return 0;
}

// Real AOT: parse ahead of time, then emit C++ that rebuilds the AST at startup
// and interprets it (no lexing/parsing in the produced binary). Falls back to
// source bundling for any construct the AST emitter can't reconstruct.
static int compileAotAst(const std::string& src, const std::string& srcName, std::string outPath, const std::string& selfExe) {
    if (outPath.empty()) outPath = defaultOut(srcName);
    std::string cpp, finish;
    try {
        Lexer lexer(src);
        Parser parser(lexer.tokenize());
        finish = lexer.finishData();
        Program prog = parser.parseProgram();
        std::ostringstream ss;
        emitAstProgram(prog, ss, baseOf(srcName), finish);
        cpp = ss.str();
    } catch (const ParseError& e) {
        std::cerr << "===SORRY!=== Parse error at line " << e.line << ": " << e.what() << "\n";
        return 2;
    } catch (const AstEmitError& e) {
        std::cerr << "note: " << e.msg << " — falling back to source bundling.\n";
        return compileToExe(src, srcName, outPath, selfExe);
    }

    std::string dir = dirOf(selfExe);
    std::string lib = dir + "/librakupp_rt.a", inc = dir + "/../src";
    if (std::ifstream(lib).good() == false) { std::cerr << "Cannot find runtime library: " << lib << "\n"; return 5; }
    std::string genPath = outPath + ".rakupp.ast.cpp";
    { std::ofstream g(genPath); if (!g) { std::cerr << "Cannot write " << genPath << "\n"; return 5; } g << cpp; }
    const char* cxxEnv = std::getenv("CXX");
    std::string cxx = cxxEnv && *cxxEnv ? cxxEnv : "c++";
    std::string cmd = cxx + " -std=c++17 -O2 -w -pthread -Wl,-w -I " + shq(inc) + " " + shq(genPath) + " " + shq(lib) + " -o " + shq(outPath);
    int rc = std::system(cmd.c_str());
    if (!std::getenv("RAKUPP_KEEPGEN")) std::remove(genPath.c_str());
    if (rc != 0) { std::cerr << "Compilation failed (compiler exit " << rc << ")\n"; return 5; }
    std::cerr << "Compiled (AOT) " << srcName << " -> " << outPath << "\n";
    return 0;
}

// ---------------------------------------------------------------------------

int main(int argc, char** argv) {
    std::string exePath = argv[0] ? argv[0] : "rakupp";
    { char rp[4096]; if (realpath(exePath.c_str(), rp)) exePath = rp; }

    // --dump-ast FILE | --dump-ast -e CODE : print the parsed AST and exit
    if (argc >= 2 && std::string(argv[1]) == "--dump-ast") {
        std::string src, fname = "-e";
        if (argc >= 4 && std::string(argv[2]) == "-e") src = argv[3];
        else if (argc >= 3) {
            std::ifstream in(argv[2]);
            if (!in) { std::cerr << "Cannot open file: " << argv[2] << "\n"; return 4; }
            std::ostringstream ss; ss << in.rdbuf(); src = ss.str(); fname = argv[2];
        } else { std::cerr << "Usage: rakupp --dump-ast FILE | --dump-ast -e CODE\n"; return 4; }
        try {
            Lexer lexer(src);
            Parser parser(lexer.tokenize());
            Program prog = parser.parseProgram();
            dumpAst(prog, std::cout);
        } catch (const ParseError& e) {
            std::cerr << "===SORRY!=== Parse error at line " << e.line << ": " << e.what() << "\n";
            return 2;
        }
        return 0;
    }

    // --bundle : embed program source + runtime interpreter (parses at run time)
    // --aot    : parse ahead of time, embed the AST, interpret it (no run-time parse)
    // --exe    : native transpilation to C++ (no interpreter inside)
    //   each: (FILE | -e CODE) [-o OUT]
    {
        std::string mode = argc >= 2 ? argv[1] : "";
        if (mode == "--bundle" || mode == "--aot" || mode == "--exe") {
            std::string src, srcName, outPath;
            bool haveSrc = false;
            for (int i = 2; i < argc; i++) {
                std::string a = argv[i];
                if (a == "-o" && i + 1 < argc) { outPath = argv[++i]; }
                else if (a.rfind("-o", 0) == 0 && a.size() > 2) { outPath = a.substr(2); }
                else if (a == "-e" && i + 1 < argc) { src = argv[++i]; srcName = "-e"; haveSrc = true; }
                else if (a.rfind("-e", 0) == 0 && a.size() > 2) { src = a.substr(2); srcName = "-e"; haveSrc = true; }
                else if (!haveSrc) { // a source file
                    std::ifstream in(a);
                    if (!in) { std::cerr << "Cannot open file: " << a << "\n"; return 4; }
                    std::ostringstream ss; ss << in.rdbuf(); src = ss.str(); srcName = a; haveSrc = true;
                }
            }
            if (!haveSrc) { std::cerr << "Usage: rakupp " << mode << " (FILE | -e CODE) [-o OUT]\n"; return 4; }
            if (mode == "--exe") return compileNative(src, srcName, outPath, exePath);
            if (mode == "--aot") return compileAotAst(src, srcName, outPath, exePath);
            return compileToExe(src, srcName, outPath, exePath); // --bundle
        }
    }

    std::string src;
    std::string fileName = "-e";
    std::vector<std::string> args;
    if (argc >= 2 && std::string(argv[1]).rfind("-e", 0) == 0) {
        std::string a1 = argv[1];
        if (a1 == "-e") {              // `-e CODE` : code is the next argument
            if (argc < 3) { std::cerr << "No code given for -e\n"; return 4; }
            src = argv[2];
            for (int i = 3; i < argc; i++) args.push_back(argv[i]);
        } else {                       // `-e'CODE'` / `-eCODE` : code attached to the flag
            src = a1.substr(2);
            for (int i = 2; i < argc; i++) args.push_back(argv[i]);
        }
    } else if (argc >= 2) {
        std::ifstream in(argv[1]);
        if (!in) { std::cerr << "Cannot open file: " << argv[1] << "\n"; return 4; }
        std::ostringstream ss;
        ss << in.rdbuf();
        src = ss.str();
        fileName = argv[1];
        for (int i = 2; i < argc; i++) args.push_back(argv[i]);
    } else {
        std::ostringstream ss;
        ss << std::cin.rdbuf();
        src = ss.str();
    }
    return rakuppRunBigStack(src, std::move(args), fileName, exePath);
}
