// The RakuAST:: class registry (RAKUAST-PLAN P0).
//
// Rakudo's RakuAST is Raku's own syntax tree, reachable from Raku itself. A
// module that uses it does not degrade here, it hard-fails, so the names have
// to exist — `RakuAST::IntLiteral`, `$node ~~ RakuAST::Expression`, `.^mro`.
//
// They live in their OWN immutable map, never in the interpreter's `classes_`,
// for three reasons that are all load-bearing:
//
//   * executing 113 ClassDecls would tail-alias bare `Statement` / `Expression`
//     / `Call` into general resolution — a semantics leak into every program;
//   * seeding `classes_` lazily is a data race: in default parallel mode the
//     GIL is never taken for compute, so inserting into that map while workers
//     read it lock-free is the rehash-under-reader crash `noteSymbolMutation`
//     exists to police. Here the whole map is built and published in ONE
//     release-store (the PublishedOnce idiom), which is safe post-freeze;
//   * `resolveClassAlias`'s suffix scan never sees these names, so a user's
//     `Foo::Call` can never mis-alias to `RakuAST::Call` — and a user's own
//     `class RakuAST::Mine {}` lives in `classes_` and shadows naturally,
//     with no exclusion code on either side.
//
// Consulted ONLY where `classes_` has already missed, behind the pragma gate
// (`use experimental :rakuast`, or 6.e), so a program that never mentions the
// namespace does no work at all.
//
// The table itself is MEASURED, not invented: `src/rakuast-classes.inc` is
// generated by tools/rakuast-class-table.raku from the installed Rakudo. See
// that file for what the class set is and why.
#pragma once

#include <iosfwd>
#include <memory>
#include <string>
#include <vector>

#include "Value.h"

namespace rakupp {

struct ClassInfo;

// The namespace prefix, and the cheap test every miss path runs first. Kept
// inline and header-only so the runtime side can ask without linking the
// registry TU at all (`--slim` binaries that cut the parser still compile it).
inline constexpr const char* kRakuAstPrefix = "RakuAST::";
inline bool isRakuAstName(const std::string& n) {
    return n.size() > 9 && n.compare(0, 9, kRakuAstPrefix) == 0;
}

// The registry's ClassInfo for a fully qualified `RakuAST::…` name, or null
// when the registry does not carry it. Materializes on first call.
//
// A POINTER to the registry's own shared_ptr, not a copy of it: the callers are
// method dispatch and name resolution, and a local shared_ptr there would be
// constructed and destroyed on every method call that reaches the arm — which
// measured as a few percent on object construction. The pointee lives as long
// as the process.
const std::shared_ptr<ClassInfo>* rakuAstClass(const std::string& qualifiedName);

// Rakudo's own linearization for a fully qualified `RakuAST::…` name: the
// class itself first, then its ancestors as `.^parents` gives them, then `Any`
// and `Mu` — i.e. exactly `.^mro`. Empty when the registry does not carry the
// name. The list is REPRODUCED rather than derived: the chains are C3 over
// roles, and a subclass's tail is not its parent's chain.
const std::vector<std::string>& rakuAstAncestry(const std::string& qualifiedName);

// Construct a node: `RakuAST::Foo.new(…)`. Positional arguments land in the
// slot Rakudo gives that class a positional for; every named argument keeps its
// own key. Throws X::Constructor::Positional for a class with no positional
// constructor, exactly as the default `new` does.
Value rakuAstNew(Interpreter& I, const std::string& qualifiedName, ValueList& args);

// Render a node back to Raku source. This is the bridge P3's `.EVAL` runs over,
// so its contract is correct Raku first and Rakudo's exact spelling second; the
// measured spellings are in docs/dev/findings/rakuast/deparse-2026.08.tsv.
// Throws X::NYI, naming the class, for anything not covered — never a wrong
// rendering.
std::string rakuAstDeparse(Interpreter& I, const Value& node);

// `'source'.AST` — build the VIEW over our own parse of `source`. With
// `compUnit` it is wrapped in a `RakuAST::CompUnit`, which is what
// `.AST(:compunit)` answers and what Needle::Compile unshifts a statement into.
// Lexer and Parser only: no BEGIN runs and no undeclared-name check fires, both
// recorded divergences from Rakudo.
Value rakuAstView(Interpreter& I, const std::string& source, bool compUnit);

// `RakuAST::Name.from-identifier(…)` and `.from-identifier-parts(…)`, the
// spelling every dist uses to make a name.
Value rakuAstNameFrom(Interpreter& I, const ValueList& parts);

// `rakupp --rakuast SRC` — print the VIEW as an indented tree, the sibling of
// `--ast`. With `compUnit` the `:compunit` shape; with `withAttrs` each node's
// scalar attributes follow its class name.
void dumpRakuAst(Interpreter& I, const std::string& source, std::ostream& out,
                 bool compUnit, bool withAttrs);

// Run a tree: render it and hand the text to the ordinary parser, in the
// CALLER's lexical scope. Live values the text cannot carry ride a side table
// bound into a child scope, so a closure or an object survives the trip with
// its identity intact. Both spellings route here — the `.EVAL` method on a node
// and the `EVAL $node` sub form.
Value rakuAstEval(Interpreter& I, const Value& node);

// Build the registry now. Called when the parser has flagged a unit as using
// RakuAST, so the single publish happens on the thread that runs the unit
// rather than in whichever worker first misses.
void rakuAstMaterialize();

} // namespace rakupp
