# Build identity: `git describe --always --dirty` and the build date, written to
# a generated header.
#
# Run as a SCRIPT (cmake -P) from a custom target, not at configure time, so the
# values cannot go stale: `cmake --build` after a commit would otherwise keep
# reporting whatever HEAD was when cmake last ran, which is exactly the failure
# this is meant to remove.
#
# The header is written through copy_if_different, so an unchanged build (same
# commit, same day) leaves the timestamp alone and nothing recompiles. Only
# BuildInfo.cpp includes it, so even a real change rebuilds one file.
#
# Expects: SRC_DIR (repo root), OUT_FILE (header to write).

set(RAKUPP_BUILD "unknown")
find_package(Git QUIET)
if(GIT_FOUND AND EXISTS "${SRC_DIR}/.git")
  execute_process(
    COMMAND "${GIT_EXECUTABLE}" describe --always --dirty
    WORKING_DIRECTORY "${SRC_DIR}"
    OUTPUT_VARIABLE _desc
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE _rc)
  if(_rc EQUAL 0 AND _desc)
    set(RAKUPP_BUILD "${_desc}")
  endif()
endif()

# A source tarball has no .git and no commits to describe; say so plainly rather
# than inventing an identity a user could mistake for a real one.
string(TIMESTAMP RAKUPP_BUILD_DATE "%Y-%m-%d" UTC)

set(_content "// Generated by cmake/BuildInfo.cmake — do not edit, do not commit.
#pragma once
#define RAKUPP_BUILD \"${RAKUPP_BUILD}\"
#define RAKUPP_BUILD_DATE \"${RAKUPP_BUILD_DATE}\"
")

set(_tmp "${OUT_FILE}.tmp")
file(WRITE "${_tmp}" "${_content}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${_tmp}" "${OUT_FILE}")
file(REMOVE "${_tmp}")
